/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomDomain model module.
 * @module model/CustomDomain
 * @version 1.0.0
 */
class CustomDomain {
    /**
     * Constructs a new <code>CustomDomain</code>.
     * @alias module:model/CustomDomain
     */
    constructor() { 
        
        CustomDomain.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomDomain</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomDomain} obj Optional instance to populate.
     * @return {module:model/CustomDomain} The populated <code>CustomDomain</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomDomain();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('scheme')) {
                obj['scheme'] = ApiClient.convertToType(data['scheme'], 'String');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('custom_index_url')) {
                obj['custom_index_url'] = ApiClient.convertToType(data['custom_index_url'], 'String');
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'String');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomDomain</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomDomain</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['scheme'] && !(typeof data['scheme'] === 'string' || data['scheme'] instanceof String)) {
            throw new Error("Expected the field `scheme` to be a primitive type in the JSON string but got " + data['scheme']);
        }
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }
        // ensure the json data is a string
        if (data['custom_index_url'] && !(typeof data['custom_index_url'] === 'string' || data['custom_index_url'] instanceof String)) {
            throw new Error("Expected the field `custom_index_url` to be a primitive type in the JSON string but got " + data['custom_index_url']);
        }
        // ensure the json data is a string
        if (data['last_datetime'] && !(typeof data['last_datetime'] === 'string' || data['last_datetime'] instanceof String)) {
            throw new Error("Expected the field `last_datetime` to be a primitive type in the JSON string but got " + data['last_datetime']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
CustomDomain.prototype['id'] = undefined;

/**
 * @member {String} scheme
 */
CustomDomain.prototype['scheme'] = undefined;

/**
 * @member {String} host
 */
CustomDomain.prototype['host'] = undefined;

/**
 * @member {String} custom_index_url
 */
CustomDomain.prototype['custom_index_url'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
CustomDomain.prototype['is_enabled'] = undefined;

/**
 * @member {String} last_datetime
 */
CustomDomain.prototype['last_datetime'] = undefined;

/**
 * @member {Date} datetime
 */
CustomDomain.prototype['datetime'] = undefined;






export default CustomDomain;

