/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DNSRecordA from './DNSRecordA';

/**
 * The DNSMonitorDns model module.
 * @module model/DNSMonitorDns
 * @version 1.0.0
 */
class DNSMonitorDns {
    /**
     * Constructs a new <code>DNSMonitorDns</code>.
     * @alias module:model/DNSMonitorDns
     */
    constructor() { 
        
        DNSMonitorDns.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DNSMonitorDns</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DNSMonitorDns} obj Optional instance to populate.
     * @return {module:model/DNSMonitorDns} The populated <code>DNSMonitorDns</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DNSMonitorDns();

            if (data.hasOwnProperty('A')) {
                obj['A'] = ApiClient.convertToType(data['A'], [DNSRecordA]);
            }
            if (data.hasOwnProperty('CNAME')) {
                obj['CNAME'] = ApiClient.convertToType(data['CNAME'], [Object]);
            }
            if (data.hasOwnProperty('HINFO')) {
                obj['HINFO'] = ApiClient.convertToType(data['HINFO'], [Object]);
            }
            if (data.hasOwnProperty('CAA')) {
                obj['CAA'] = ApiClient.convertToType(data['CAA'], [Object]);
            }
            if (data.hasOwnProperty('MX')) {
                obj['MX'] = ApiClient.convertToType(data['MX'], [Object]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DNSMonitorDns</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DNSMonitorDns</code>.
     */
    static validateJSON(data) {
        if (data['A']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['A'])) {
                throw new Error("Expected the field `A` to be an array in the JSON data but got " + data['A']);
            }
            // validate the optional field `A` (array)
            for (const item of data['A']) {
                DNSRecordA.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['CNAME'])) {
            throw new Error("Expected the field `CNAME` to be an array in the JSON data but got " + data['CNAME']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['HINFO'])) {
            throw new Error("Expected the field `HINFO` to be an array in the JSON data but got " + data['HINFO']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['CAA'])) {
            throw new Error("Expected the field `CAA` to be an array in the JSON data but got " + data['CAA']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['MX'])) {
            throw new Error("Expected the field `MX` to be an array in the JSON data but got " + data['MX']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/DNSRecordA>} A
 */
DNSMonitorDns.prototype['A'] = undefined;

/**
 * @member {Array.<Object>} CNAME
 */
DNSMonitorDns.prototype['CNAME'] = undefined;

/**
 * @member {Array.<Object>} HINFO
 */
DNSMonitorDns.prototype['HINFO'] = undefined;

/**
 * @member {Array.<Object>} CAA
 */
DNSMonitorDns.prototype['CAA'] = undefined;

/**
 * @member {Array.<Object>} MX
 */
DNSMonitorDns.prototype['MX'] = undefined;






export default DNSMonitorDns;

