/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DNSMonitorDns from './DNSMonitorDns';
import DNSMonitorSettings from './DNSMonitorSettings';

/**
 * The DNSMonitor model module.
 * @module model/DNSMonitor
 * @version 1.0.0
 */
class DNSMonitor {
    /**
     * Constructs a new <code>DNSMonitor</code>.
     * @alias module:model/DNSMonitor
     */
    constructor() { 
        
        DNSMonitor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DNSMonitor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DNSMonitor} obj Optional instance to populate.
     * @return {module:model/DNSMonitor} The populated <code>DNSMonitor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DNSMonitor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('dns')) {
                obj['dns'] = DNSMonitorDns.constructFromObject(data['dns']);
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = ApiClient.convertToType(data['notifications'], ['Number']);
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = DNSMonitorSettings.constructFromObject(data['settings']);
            }
            if (data.hasOwnProperty('total_checks')) {
                obj['total_checks'] = ApiClient.convertToType(data['total_checks'], 'Number');
            }
            if (data.hasOwnProperty('total_changes')) {
                obj['total_changes'] = ApiClient.convertToType(data['total_changes'], 'Number');
            }
            if (data.hasOwnProperty('last_check_datetime')) {
                obj['last_check_datetime'] = ApiClient.convertToType(data['last_check_datetime'], 'Date');
            }
            if (data.hasOwnProperty('next_check_datetime')) {
                obj['next_check_datetime'] = ApiClient.convertToType(data['next_check_datetime'], 'Date');
            }
            if (data.hasOwnProperty('last_change_datetime')) {
                obj['last_change_datetime'] = ApiClient.convertToType(data['last_change_datetime'], 'String');
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DNSMonitor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DNSMonitor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        // validate the optional field `dns`
        if (data['dns']) { // data not null
          DNSMonitorDns.validateJSON(data['dns']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['notifications'])) {
            throw new Error("Expected the field `notifications` to be an array in the JSON data but got " + data['notifications']);
        }
        // validate the optional field `settings`
        if (data['settings']) { // data not null
          DNSMonitorSettings.validateJSON(data['settings']);
        }
        // ensure the json data is a string
        if (data['last_change_datetime'] && !(typeof data['last_change_datetime'] === 'string' || data['last_change_datetime'] instanceof String)) {
            throw new Error("Expected the field `last_change_datetime` to be a primitive type in the JSON string but got " + data['last_change_datetime']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
DNSMonitor.prototype['id'] = undefined;

/**
 * @member {Number} project_id
 */
DNSMonitor.prototype['project_id'] = undefined;

/**
 * @member {String} name
 */
DNSMonitor.prototype['name'] = undefined;

/**
 * @member {String} target
 */
DNSMonitor.prototype['target'] = undefined;

/**
 * @member {module:model/DNSMonitorDns} dns
 */
DNSMonitor.prototype['dns'] = undefined;

/**
 * @member {Array.<Number>} notifications
 */
DNSMonitor.prototype['notifications'] = undefined;

/**
 * @member {module:model/DNSMonitorSettings} settings
 */
DNSMonitor.prototype['settings'] = undefined;

/**
 * @member {Number} total_checks
 */
DNSMonitor.prototype['total_checks'] = undefined;

/**
 * @member {Number} total_changes
 */
DNSMonitor.prototype['total_changes'] = undefined;

/**
 * @member {Date} last_check_datetime
 */
DNSMonitor.prototype['last_check_datetime'] = undefined;

/**
 * @member {Date} next_check_datetime
 */
DNSMonitor.prototype['next_check_datetime'] = undefined;

/**
 * @member {String} last_change_datetime
 */
DNSMonitor.prototype['last_change_datetime'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
DNSMonitor.prototype['is_enabled'] = undefined;

/**
 * @member {Date} datetime
 */
DNSMonitor.prototype['datetime'] = undefined;

/**
 * @member {Date} last_datetime
 */
DNSMonitor.prototype['last_datetime'] = undefined;






export default DNSMonitor;

