/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DNSMonitorSettings model module.
 * @module model/DNSMonitorSettings
 * @version 1.0.0
 */
class DNSMonitorSettings {
    /**
     * Constructs a new <code>DNSMonitorSettings</code>.
     * @alias module:model/DNSMonitorSettings
     */
    constructor() { 
        
        DNSMonitorSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DNSMonitorSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DNSMonitorSettings} obj Optional instance to populate.
     * @return {module:model/DNSMonitorSettings} The populated <code>DNSMonitorSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DNSMonitorSettings();

            if (data.hasOwnProperty('dns_check_interval_seconds')) {
                obj['dns_check_interval_seconds'] = ApiClient.convertToType(data['dns_check_interval_seconds'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DNSMonitorSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DNSMonitorSettings</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} dns_check_interval_seconds
 */
DNSMonitorSettings.prototype['dns_check_interval_seconds'] = undefined;






export default DNSMonitorSettings;

