/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DomainMonitorSsl from './DomainMonitorSsl';
import DomainMonitorWhois from './DomainMonitorWhois';

/**
 * The DomainMonitor model module.
 * @module model/DomainMonitor
 * @version 1.0.0
 */
class DomainMonitor {
    /**
     * Constructs a new <code>DomainMonitor</code>.
     * @alias module:model/DomainMonitor
     */
    constructor() { 
        
        DomainMonitor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainMonitor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainMonitor} obj Optional instance to populate.
     * @return {module:model/DomainMonitor} The populated <code>DomainMonitor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainMonitor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('whois')) {
                obj['whois'] = DomainMonitorWhois.constructFromObject(data['whois']);
            }
            if (data.hasOwnProperty('whois_notifications')) {
                obj['whois_notifications'] = ApiClient.convertToType(data['whois_notifications'], ['Number']);
            }
            if (data.hasOwnProperty('ssl')) {
                obj['ssl'] = DomainMonitorSsl.constructFromObject(data['ssl']);
            }
            if (data.hasOwnProperty('ssl_notifications')) {
                obj['ssl_notifications'] = ApiClient.convertToType(data['ssl_notifications'], ['Number']);
            }
            if (data.hasOwnProperty('total_checks')) {
                obj['total_checks'] = ApiClient.convertToType(data['total_checks'], 'Number');
            }
            if (data.hasOwnProperty('last_check_datetime')) {
                obj['last_check_datetime'] = ApiClient.convertToType(data['last_check_datetime'], 'Date');
            }
            if (data.hasOwnProperty('next_check_datetime')) {
                obj['next_check_datetime'] = ApiClient.convertToType(data['next_check_datetime'], 'Date');
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'String');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DomainMonitor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DomainMonitor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        // validate the optional field `whois`
        if (data['whois']) { // data not null
          DomainMonitorWhois.validateJSON(data['whois']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['whois_notifications'])) {
            throw new Error("Expected the field `whois_notifications` to be an array in the JSON data but got " + data['whois_notifications']);
        }
        // validate the optional field `ssl`
        if (data['ssl']) { // data not null
          DomainMonitorSsl.validateJSON(data['ssl']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ssl_notifications'])) {
            throw new Error("Expected the field `ssl_notifications` to be an array in the JSON data but got " + data['ssl_notifications']);
        }
        // ensure the json data is a string
        if (data['last_datetime'] && !(typeof data['last_datetime'] === 'string' || data['last_datetime'] instanceof String)) {
            throw new Error("Expected the field `last_datetime` to be a primitive type in the JSON string but got " + data['last_datetime']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
DomainMonitor.prototype['id'] = undefined;

/**
 * @member {Number} project_id
 */
DomainMonitor.prototype['project_id'] = undefined;

/**
 * @member {String} name
 */
DomainMonitor.prototype['name'] = undefined;

/**
 * @member {String} target
 */
DomainMonitor.prototype['target'] = undefined;

/**
 * @member {module:model/DomainMonitorWhois} whois
 */
DomainMonitor.prototype['whois'] = undefined;

/**
 * @member {Array.<Number>} whois_notifications
 */
DomainMonitor.prototype['whois_notifications'] = undefined;

/**
 * @member {module:model/DomainMonitorSsl} ssl
 */
DomainMonitor.prototype['ssl'] = undefined;

/**
 * @member {Array.<Number>} ssl_notifications
 */
DomainMonitor.prototype['ssl_notifications'] = undefined;

/**
 * @member {Number} total_checks
 */
DomainMonitor.prototype['total_checks'] = undefined;

/**
 * @member {Date} last_check_datetime
 */
DomainMonitor.prototype['last_check_datetime'] = undefined;

/**
 * @member {Date} next_check_datetime
 */
DomainMonitor.prototype['next_check_datetime'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
DomainMonitor.prototype['is_enabled'] = undefined;

/**
 * @member {String} last_datetime
 */
DomainMonitor.prototype['last_datetime'] = undefined;

/**
 * @member {Date} datetime
 */
DomainMonitor.prototype['datetime'] = undefined;






export default DomainMonitor;

