/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DomainMonitor from './DomainMonitor';
import MonitorsGet200ResponseLinks from './MonitorsGet200ResponseLinks';
import MonitorsGet200ResponseMeta from './MonitorsGet200ResponseMeta';

/**
 * The DomainNamesGet200Response model module.
 * @module model/DomainNamesGet200Response
 * @version 1.0.0
 */
class DomainNamesGet200Response {
    /**
     * Constructs a new <code>DomainNamesGet200Response</code>.
     * @alias module:model/DomainNamesGet200Response
     */
    constructor() { 
        
        DomainNamesGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainNamesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainNamesGet200Response} obj Optional instance to populate.
     * @return {module:model/DomainNamesGet200Response} The populated <code>DomainNamesGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainNamesGet200Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [DomainMonitor]);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = MonitorsGet200ResponseMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = MonitorsGet200ResponseLinks.constructFromObject(data['links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DomainNamesGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DomainNamesGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                DomainMonitor.validateJSON(item);
            };
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          MonitorsGet200ResponseMeta.validateJSON(data['meta']);
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          MonitorsGet200ResponseLinks.validateJSON(data['links']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/DomainMonitor>} data
 */
DomainNamesGet200Response.prototype['data'] = undefined;

/**
 * @member {module:model/MonitorsGet200ResponseMeta} meta
 */
DomainNamesGet200Response.prototype['meta'] = undefined;

/**
 * @member {module:model/MonitorsGet200ResponseLinks} links
 */
DomainNamesGet200Response.prototype['links'] = undefined;






export default DomainNamesGet200Response;

