/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DomainMonitorWhois model module.
 * @module model/DomainMonitorWhois
 * @version 1.0.0
 */
class DomainMonitorWhois {
    /**
     * Constructs a new <code>DomainMonitorWhois</code>.
     * @alias module:model/DomainMonitorWhois
     */
    constructor() { 
        
        DomainMonitorWhois.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainMonitorWhois</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainMonitorWhois} obj Optional instance to populate.
     * @return {module:model/DomainMonitorWhois} The populated <code>DomainMonitorWhois</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainMonitorWhois();

            if (data.hasOwnProperty('start_datetime')) {
                obj['start_datetime'] = ApiClient.convertToType(data['start_datetime'], 'Date');
            }
            if (data.hasOwnProperty('updated_datetime')) {
                obj['updated_datetime'] = ApiClient.convertToType(data['updated_datetime'], 'Date');
            }
            if (data.hasOwnProperty('end_datetime')) {
                obj['end_datetime'] = ApiClient.convertToType(data['end_datetime'], 'Date');
            }
            if (data.hasOwnProperty('registrar')) {
                obj['registrar'] = ApiClient.convertToType(data['registrar'], 'String');
            }
            if (data.hasOwnProperty('nameservers')) {
                obj['nameservers'] = ApiClient.convertToType(data['nameservers'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DomainMonitorWhois</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DomainMonitorWhois</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['registrar'] && !(typeof data['registrar'] === 'string' || data['registrar'] instanceof String)) {
            throw new Error("Expected the field `registrar` to be a primitive type in the JSON string but got " + data['registrar']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['nameservers'])) {
            throw new Error("Expected the field `nameservers` to be an array in the JSON data but got " + data['nameservers']);
        }

        return true;
    }


}



/**
 * @member {Date} start_datetime
 */
DomainMonitorWhois.prototype['start_datetime'] = undefined;

/**
 * @member {Date} updated_datetime
 */
DomainMonitorWhois.prototype['updated_datetime'] = undefined;

/**
 * @member {Date} end_datetime
 */
DomainMonitorWhois.prototype['end_datetime'] = undefined;

/**
 * @member {String} registrar
 */
DomainMonitorWhois.prototype['registrar'] = undefined;

/**
 * @member {Array.<String>} nameservers
 */
DomainMonitorWhois.prototype['nameservers'] = undefined;






export default DomainMonitorWhois;

