/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DomainMonitorSsl model module.
 * @module model/DomainMonitorSsl
 * @version 1.0.0
 */
class DomainMonitorSsl {
    /**
     * Constructs a new <code>DomainMonitorSsl</code>.
     * @alias module:model/DomainMonitorSsl
     */
    constructor() { 
        
        DomainMonitorSsl.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainMonitorSsl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainMonitorSsl} obj Optional instance to populate.
     * @return {module:model/DomainMonitorSsl} The populated <code>DomainMonitorSsl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainMonitorSsl();

            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
            }
            if (data.hasOwnProperty('common_name')) {
                obj['common_name'] = ApiClient.convertToType(data['common_name'], 'String');
            }
            if (data.hasOwnProperty('start_datetime')) {
                obj['start_datetime'] = ApiClient.convertToType(data['start_datetime'], 'Date');
            }
            if (data.hasOwnProperty('end_datetime')) {
                obj['end_datetime'] = ApiClient.convertToType(data['end_datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DomainMonitorSsl</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DomainMonitorSsl</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['organization'] && !(typeof data['organization'] === 'string' || data['organization'] instanceof String)) {
            throw new Error("Expected the field `organization` to be a primitive type in the JSON string but got " + data['organization']);
        }
        // ensure the json data is a string
        if (data['common_name'] && !(typeof data['common_name'] === 'string' || data['common_name'] instanceof String)) {
            throw new Error("Expected the field `common_name` to be a primitive type in the JSON string but got " + data['common_name']);
        }

        return true;
    }


}



/**
 * @member {String} organization
 */
DomainMonitorSsl.prototype['organization'] = undefined;

/**
 * @member {String} common_name
 */
DomainMonitorSsl.prototype['common_name'] = undefined;

/**
 * @member {Date} start_datetime
 */
DomainMonitorSsl.prototype['start_datetime'] = undefined;

/**
 * @member {Date} end_datetime
 */
DomainMonitorSsl.prototype['end_datetime'] = undefined;






export default DomainMonitorSsl;

