/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DomainMonitor from './DomainMonitor';

/**
 * The DomainNamesDomainNameIdGet200Response model module.
 * @module model/DomainNamesDomainNameIdGet200Response
 * @version 1.0.0
 */
class DomainNamesDomainNameIdGet200Response {
    /**
     * Constructs a new <code>DomainNamesDomainNameIdGet200Response</code>.
     * @alias module:model/DomainNamesDomainNameIdGet200Response
     */
    constructor() { 
        
        DomainNamesDomainNameIdGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainNamesDomainNameIdGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainNamesDomainNameIdGet200Response} obj Optional instance to populate.
     * @return {module:model/DomainNamesDomainNameIdGet200Response} The populated <code>DomainNamesDomainNameIdGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainNamesDomainNameIdGet200Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = DomainMonitor.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DomainNamesDomainNameIdGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DomainNamesDomainNameIdGet200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          DomainMonitor.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/DomainMonitor} data
 */
DomainNamesDomainNameIdGet200Response.prototype['data'] = undefined;






export default DomainNamesDomainNameIdGet200Response;

