/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HeartbeatMonitorSettings model module.
 * @module model/HeartbeatMonitorSettings
 * @version 1.0.0
 */
class HeartbeatMonitorSettings {
    /**
     * Constructs a new <code>HeartbeatMonitorSettings</code>.
     * @alias module:model/HeartbeatMonitorSettings
     */
    constructor() { 
        
        HeartbeatMonitorSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HeartbeatMonitorSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HeartbeatMonitorSettings} obj Optional instance to populate.
     * @return {module:model/HeartbeatMonitorSettings} The populated <code>HeartbeatMonitorSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HeartbeatMonitorSettings();

            if (data.hasOwnProperty('run_interval')) {
                obj['run_interval'] = ApiClient.convertToType(data['run_interval'], 'Number');
            }
            if (data.hasOwnProperty('run_interval_type')) {
                obj['run_interval_type'] = ApiClient.convertToType(data['run_interval_type'], 'String');
            }
            if (data.hasOwnProperty('run_interval_grace')) {
                obj['run_interval_grace'] = ApiClient.convertToType(data['run_interval_grace'], 'Number');
            }
            if (data.hasOwnProperty('run_interval_grace_type')) {
                obj['run_interval_grace_type'] = ApiClient.convertToType(data['run_interval_grace_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HeartbeatMonitorSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HeartbeatMonitorSettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['run_interval_type'] && !(typeof data['run_interval_type'] === 'string' || data['run_interval_type'] instanceof String)) {
            throw new Error("Expected the field `run_interval_type` to be a primitive type in the JSON string but got " + data['run_interval_type']);
        }
        // ensure the json data is a string
        if (data['run_interval_grace_type'] && !(typeof data['run_interval_grace_type'] === 'string' || data['run_interval_grace_type'] instanceof String)) {
            throw new Error("Expected the field `run_interval_grace_type` to be a primitive type in the JSON string but got " + data['run_interval_grace_type']);
        }

        return true;
    }


}



/**
 * @member {Number} run_interval
 */
HeartbeatMonitorSettings.prototype['run_interval'] = undefined;

/**
 * @member {module:model/HeartbeatMonitorSettings.RunIntervalTypeEnum} run_interval_type
 */
HeartbeatMonitorSettings.prototype['run_interval_type'] = undefined;

/**
 * @member {Number} run_interval_grace
 */
HeartbeatMonitorSettings.prototype['run_interval_grace'] = undefined;

/**
 * @member {module:model/HeartbeatMonitorSettings.RunIntervalGraceTypeEnum} run_interval_grace_type
 */
HeartbeatMonitorSettings.prototype['run_interval_grace_type'] = undefined;





/**
 * Allowed values for the <code>run_interval_type</code> property.
 * @enum {String}
 * @readonly
 */
HeartbeatMonitorSettings['RunIntervalTypeEnum'] = {

    /**
     * value: "seconds"
     * @const
     */
    "seconds": "seconds",

    /**
     * value: "minutes"
     * @const
     */
    "minutes": "minutes",

    /**
     * value: "hours"
     * @const
     */
    "hours": "hours",

    /**
     * value: "days"
     * @const
     */
    "days": "days"
};


/**
 * Allowed values for the <code>run_interval_grace_type</code> property.
 * @enum {String}
 * @readonly
 */
HeartbeatMonitorSettings['RunIntervalGraceTypeEnum'] = {

    /**
     * value: "seconds"
     * @const
     */
    "seconds": "seconds",

    /**
     * value: "minutes"
     * @const
     */
    "minutes": "minutes",

    /**
     * value: "hours"
     * @const
     */
    "hours": "hours",

    /**
     * value: "days"
     * @const
     */
    "days": "days"
};



export default HeartbeatMonitorSettings;

