/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HeartbeatMonitorSettings from './HeartbeatMonitorSettings';
import MonitorNotifications from './MonitorNotifications';

/**
 * The HeartbeatMonitor model module.
 * @module model/HeartbeatMonitor
 * @version 1.0.0
 */
class HeartbeatMonitor {
    /**
     * Constructs a new <code>HeartbeatMonitor</code>.
     * @alias module:model/HeartbeatMonitor
     */
    constructor() { 
        
        HeartbeatMonitor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HeartbeatMonitor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HeartbeatMonitor} obj Optional instance to populate.
     * @return {module:model/HeartbeatMonitor} The populated <code>HeartbeatMonitor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HeartbeatMonitor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = HeartbeatMonitorSettings.constructFromObject(data['settings']);
            }
            if (data.hasOwnProperty('is_ok')) {
                obj['is_ok'] = ApiClient.convertToType(data['is_ok'], 'Number');
            }
            if (data.hasOwnProperty('uptime')) {
                obj['uptime'] = ApiClient.convertToType(data['uptime'], 'Number');
            }
            if (data.hasOwnProperty('downtime')) {
                obj['downtime'] = ApiClient.convertToType(data['downtime'], 'Number');
            }
            if (data.hasOwnProperty('total_runs')) {
                obj['total_runs'] = ApiClient.convertToType(data['total_runs'], 'Number');
            }
            if (data.hasOwnProperty('total_missed_runs')) {
                obj['total_missed_runs'] = ApiClient.convertToType(data['total_missed_runs'], 'Number');
            }
            if (data.hasOwnProperty('last_run_datetime')) {
                obj['last_run_datetime'] = ApiClient.convertToType(data['last_run_datetime'], 'Date');
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = MonitorNotifications.constructFromObject(data['notifications']);
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HeartbeatMonitor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HeartbeatMonitor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // validate the optional field `settings`
        if (data['settings']) { // data not null
          HeartbeatMonitorSettings.validateJSON(data['settings']);
        }
        // validate the optional field `notifications`
        if (data['notifications']) { // data not null
          MonitorNotifications.validateJSON(data['notifications']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
HeartbeatMonitor.prototype['id'] = undefined;

/**
 * @member {Number} project_id
 */
HeartbeatMonitor.prototype['project_id'] = undefined;

/**
 * @member {String} name
 */
HeartbeatMonitor.prototype['name'] = undefined;

/**
 * @member {String} code
 */
HeartbeatMonitor.prototype['code'] = undefined;

/**
 * @member {module:model/HeartbeatMonitorSettings} settings
 */
HeartbeatMonitor.prototype['settings'] = undefined;

/**
 * @member {Number} is_ok
 */
HeartbeatMonitor.prototype['is_ok'] = undefined;

/**
 * @member {Number} uptime
 */
HeartbeatMonitor.prototype['uptime'] = undefined;

/**
 * @member {Number} downtime
 */
HeartbeatMonitor.prototype['downtime'] = undefined;

/**
 * @member {Number} total_runs
 */
HeartbeatMonitor.prototype['total_runs'] = undefined;

/**
 * @member {Number} total_missed_runs
 */
HeartbeatMonitor.prototype['total_missed_runs'] = undefined;

/**
 * @member {Date} last_run_datetime
 */
HeartbeatMonitor.prototype['last_run_datetime'] = undefined;

/**
 * @member {module:model/MonitorNotifications} notifications
 */
HeartbeatMonitor.prototype['notifications'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
HeartbeatMonitor.prototype['is_enabled'] = undefined;

/**
 * @member {Date} datetime
 */
HeartbeatMonitor.prototype['datetime'] = undefined;






export default HeartbeatMonitor;

