/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MonitorsPost201ResponseData from './MonitorsPost201ResponseData';

/**
 * The MonitorsPost201Response model module.
 * @module model/MonitorsPost201Response
 * @version 1.0.0
 */
class MonitorsPost201Response {
    /**
     * Constructs a new <code>MonitorsPost201Response</code>.
     * @alias module:model/MonitorsPost201Response
     */
    constructor() { 
        
        MonitorsPost201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MonitorsPost201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MonitorsPost201Response} obj Optional instance to populate.
     * @return {module:model/MonitorsPost201Response} The populated <code>MonitorsPost201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonitorsPost201Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = MonitorsPost201ResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MonitorsPost201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MonitorsPost201Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          MonitorsPost201ResponseData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/MonitorsPost201ResponseData} data
 */
MonitorsPost201Response.prototype['data'] = undefined;






export default MonitorsPost201Response;

