/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MonitorsGet200ResponseMeta model module.
 * @module model/MonitorsGet200ResponseMeta
 * @version 1.0.0
 */
class MonitorsGet200ResponseMeta {
    /**
     * Constructs a new <code>MonitorsGet200ResponseMeta</code>.
     * @alias module:model/MonitorsGet200ResponseMeta
     */
    constructor() { 
        
        MonitorsGet200ResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MonitorsGet200ResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MonitorsGet200ResponseMeta} obj Optional instance to populate.
     * @return {module:model/MonitorsGet200ResponseMeta} The populated <code>MonitorsGet200ResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonitorsGet200ResponseMeta();

            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('results_per_page')) {
                obj['results_per_page'] = ApiClient.convertToType(data['results_per_page'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MonitorsGet200ResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MonitorsGet200ResponseMeta</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} page
 */
MonitorsGet200ResponseMeta.prototype['page'] = undefined;

/**
 * @member {Number} results_per_page
 */
MonitorsGet200ResponseMeta.prototype['results_per_page'] = undefined;

/**
 * @member {Number} total
 */
MonitorsGet200ResponseMeta.prototype['total'] = undefined;

/**
 * @member {Number} total_pages
 */
MonitorsGet200ResponseMeta.prototype['total_pages'] = undefined;






export default MonitorsGet200ResponseMeta;

