/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MonitorNotifications from './MonitorNotifications';
import MonitorSettings from './MonitorSettings';

/**
 * The Monitor model module.
 * @module model/Monitor
 * @version 1.0.0
 */
class Monitor {
    /**
     * Constructs a new <code>Monitor</code>.
     * @alias module:model/Monitor
     */
    constructor() { 
        
        Monitor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Monitor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Monitor} obj Optional instance to populate.
     * @return {module:model/Monitor} The populated <code>Monitor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Monitor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = MonitorSettings.constructFromObject(data['settings']);
            }
            if (data.hasOwnProperty('ping_servers_ids')) {
                obj['ping_servers_ids'] = ApiClient.convertToType(data['ping_servers_ids'], ['Number']);
            }
            if (data.hasOwnProperty('is_ok')) {
                obj['is_ok'] = ApiClient.convertToType(data['is_ok'], 'Number');
            }
            if (data.hasOwnProperty('uptime')) {
                obj['uptime'] = ApiClient.convertToType(data['uptime'], 'Number');
            }
            if (data.hasOwnProperty('downtime')) {
                obj['downtime'] = ApiClient.convertToType(data['downtime'], 'Number');
            }
            if (data.hasOwnProperty('average_response_time')) {
                obj['average_response_time'] = ApiClient.convertToType(data['average_response_time'], 'Number');
            }
            if (data.hasOwnProperty('total_checks')) {
                obj['total_checks'] = ApiClient.convertToType(data['total_checks'], 'Number');
            }
            if (data.hasOwnProperty('total_ok_checks')) {
                obj['total_ok_checks'] = ApiClient.convertToType(data['total_ok_checks'], 'Number');
            }
            if (data.hasOwnProperty('total_not_ok_checks')) {
                obj['total_not_ok_checks'] = ApiClient.convertToType(data['total_not_ok_checks'], 'Number');
            }
            if (data.hasOwnProperty('last_check_datetime')) {
                obj['last_check_datetime'] = ApiClient.convertToType(data['last_check_datetime'], 'Date');
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = MonitorNotifications.constructFromObject(data['notifications']);
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Monitor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Monitor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        // validate the optional field `settings`
        if (data['settings']) { // data not null
          MonitorSettings.validateJSON(data['settings']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ping_servers_ids'])) {
            throw new Error("Expected the field `ping_servers_ids` to be an array in the JSON data but got " + data['ping_servers_ids']);
        }
        // validate the optional field `notifications`
        if (data['notifications']) { // data not null
          MonitorNotifications.validateJSON(data['notifications']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Monitor.prototype['id'] = undefined;

/**
 * @member {Number} project_id
 */
Monitor.prototype['project_id'] = undefined;

/**
 * @member {String} name
 */
Monitor.prototype['name'] = undefined;

/**
 * @member {module:model/Monitor.TypeEnum} type
 */
Monitor.prototype['type'] = undefined;

/**
 * @member {String} target
 */
Monitor.prototype['target'] = undefined;

/**
 * @member {Number} port
 */
Monitor.prototype['port'] = undefined;

/**
 * @member {module:model/MonitorSettings} settings
 */
Monitor.prototype['settings'] = undefined;

/**
 * @member {Array.<Number>} ping_servers_ids
 */
Monitor.prototype['ping_servers_ids'] = undefined;

/**
 * @member {Number} is_ok
 */
Monitor.prototype['is_ok'] = undefined;

/**
 * @member {Number} uptime
 */
Monitor.prototype['uptime'] = undefined;

/**
 * @member {Number} downtime
 */
Monitor.prototype['downtime'] = undefined;

/**
 * @member {Number} average_response_time
 */
Monitor.prototype['average_response_time'] = undefined;

/**
 * @member {Number} total_checks
 */
Monitor.prototype['total_checks'] = undefined;

/**
 * @member {Number} total_ok_checks
 */
Monitor.prototype['total_ok_checks'] = undefined;

/**
 * @member {Number} total_not_ok_checks
 */
Monitor.prototype['total_not_ok_checks'] = undefined;

/**
 * @member {Date} last_check_datetime
 */
Monitor.prototype['last_check_datetime'] = undefined;

/**
 * @member {module:model/MonitorNotifications} notifications
 */
Monitor.prototype['notifications'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
Monitor.prototype['is_enabled'] = undefined;

/**
 * @member {Date} datetime
 */
Monitor.prototype['datetime'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Monitor['TypeEnum'] = {

    /**
     * value: "website"
     * @const
     */
    "website": "website",

    /**
     * value: "ping"
     * @const
     */
    "ping": "ping",

    /**
     * value: "port"
     * @const
     */
    "port": "port"
};



export default Monitor;

