/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MonitorsGet200ResponseLinks model module.
 * @module model/MonitorsGet200ResponseLinks
 * @version 1.0.0
 */
class MonitorsGet200ResponseLinks {
    /**
     * Constructs a new <code>MonitorsGet200ResponseLinks</code>.
     * @alias module:model/MonitorsGet200ResponseLinks
     */
    constructor() { 
        
        MonitorsGet200ResponseLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MonitorsGet200ResponseLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MonitorsGet200ResponseLinks} obj Optional instance to populate.
     * @return {module:model/MonitorsGet200ResponseLinks} The populated <code>MonitorsGet200ResponseLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonitorsGet200ResponseLinks();

            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'String');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'String');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('prev')) {
                obj['prev'] = ApiClient.convertToType(data['prev'], 'String');
            }
            if (data.hasOwnProperty('self')) {
                obj['self'] = ApiClient.convertToType(data['self'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MonitorsGet200ResponseLinks</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MonitorsGet200ResponseLinks</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['first'] && !(typeof data['first'] === 'string' || data['first'] instanceof String)) {
            throw new Error("Expected the field `first` to be a primitive type in the JSON string but got " + data['first']);
        }
        // ensure the json data is a string
        if (data['last'] && !(typeof data['last'] === 'string' || data['last'] instanceof String)) {
            throw new Error("Expected the field `last` to be a primitive type in the JSON string but got " + data['last']);
        }
        // ensure the json data is a string
        if (data['next'] && !(typeof data['next'] === 'string' || data['next'] instanceof String)) {
            throw new Error("Expected the field `next` to be a primitive type in the JSON string but got " + data['next']);
        }
        // ensure the json data is a string
        if (data['prev'] && !(typeof data['prev'] === 'string' || data['prev'] instanceof String)) {
            throw new Error("Expected the field `prev` to be a primitive type in the JSON string but got " + data['prev']);
        }
        // ensure the json data is a string
        if (data['self'] && !(typeof data['self'] === 'string' || data['self'] instanceof String)) {
            throw new Error("Expected the field `self` to be a primitive type in the JSON string but got " + data['self']);
        }

        return true;
    }


}



/**
 * @member {String} first
 */
MonitorsGet200ResponseLinks.prototype['first'] = undefined;

/**
 * @member {String} last
 */
MonitorsGet200ResponseLinks.prototype['last'] = undefined;

/**
 * @member {String} next
 */
MonitorsGet200ResponseLinks.prototype['next'] = undefined;

/**
 * @member {String} prev
 */
MonitorsGet200ResponseLinks.prototype['prev'] = undefined;

/**
 * @member {String} self
 */
MonitorsGet200ResponseLinks.prototype['self'] = undefined;






export default MonitorsGet200ResponseLinks;

