/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MonitorSettings model module.
 * @module model/MonitorSettings
 * @version 1.0.0
 */
class MonitorSettings {
    /**
     * Constructs a new <code>MonitorSettings</code>.
     * @alias module:model/MonitorSettings
     */
    constructor() { 
        
        MonitorSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MonitorSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MonitorSettings} obj Optional instance to populate.
     * @return {module:model/MonitorSettings} The populated <code>MonitorSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonitorSettings();

            if (data.hasOwnProperty('check_interval_seconds')) {
                obj['check_interval_seconds'] = ApiClient.convertToType(data['check_interval_seconds'], 'Number');
            }
            if (data.hasOwnProperty('timeout_seconds')) {
                obj['timeout_seconds'] = ApiClient.convertToType(data['timeout_seconds'], 'Number');
            }
            if (data.hasOwnProperty('request_method')) {
                obj['request_method'] = ApiClient.convertToType(data['request_method'], 'String');
            }
            if (data.hasOwnProperty('request_body')) {
                obj['request_body'] = ApiClient.convertToType(data['request_body'], 'String');
            }
            if (data.hasOwnProperty('request_basic_auth_username')) {
                obj['request_basic_auth_username'] = ApiClient.convertToType(data['request_basic_auth_username'], 'String');
            }
            if (data.hasOwnProperty('request_basic_auth_password')) {
                obj['request_basic_auth_password'] = ApiClient.convertToType(data['request_basic_auth_password'], 'String');
            }
            if (data.hasOwnProperty('request_headers')) {
                obj['request_headers'] = ApiClient.convertToType(data['request_headers'], ['String']);
            }
            if (data.hasOwnProperty('response_status_code')) {
                obj['response_status_code'] = ApiClient.convertToType(data['response_status_code'], 'Number');
            }
            if (data.hasOwnProperty('response_body')) {
                obj['response_body'] = ApiClient.convertToType(data['response_body'], 'String');
            }
            if (data.hasOwnProperty('response_headers')) {
                obj['response_headers'] = ApiClient.convertToType(data['response_headers'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MonitorSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MonitorSettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['request_method'] && !(typeof data['request_method'] === 'string' || data['request_method'] instanceof String)) {
            throw new Error("Expected the field `request_method` to be a primitive type in the JSON string but got " + data['request_method']);
        }
        // ensure the json data is a string
        if (data['request_body'] && !(typeof data['request_body'] === 'string' || data['request_body'] instanceof String)) {
            throw new Error("Expected the field `request_body` to be a primitive type in the JSON string but got " + data['request_body']);
        }
        // ensure the json data is a string
        if (data['request_basic_auth_username'] && !(typeof data['request_basic_auth_username'] === 'string' || data['request_basic_auth_username'] instanceof String)) {
            throw new Error("Expected the field `request_basic_auth_username` to be a primitive type in the JSON string but got " + data['request_basic_auth_username']);
        }
        // ensure the json data is a string
        if (data['request_basic_auth_password'] && !(typeof data['request_basic_auth_password'] === 'string' || data['request_basic_auth_password'] instanceof String)) {
            throw new Error("Expected the field `request_basic_auth_password` to be a primitive type in the JSON string but got " + data['request_basic_auth_password']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['request_headers'])) {
            throw new Error("Expected the field `request_headers` to be an array in the JSON data but got " + data['request_headers']);
        }
        // ensure the json data is a string
        if (data['response_body'] && !(typeof data['response_body'] === 'string' || data['response_body'] instanceof String)) {
            throw new Error("Expected the field `response_body` to be a primitive type in the JSON string but got " + data['response_body']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['response_headers'])) {
            throw new Error("Expected the field `response_headers` to be an array in the JSON data but got " + data['response_headers']);
        }

        return true;
    }


}



/**
 * @member {Number} check_interval_seconds
 */
MonitorSettings.prototype['check_interval_seconds'] = undefined;

/**
 * @member {Number} timeout_seconds
 */
MonitorSettings.prototype['timeout_seconds'] = undefined;

/**
 * @member {String} request_method
 */
MonitorSettings.prototype['request_method'] = undefined;

/**
 * @member {String} request_body
 */
MonitorSettings.prototype['request_body'] = undefined;

/**
 * @member {String} request_basic_auth_username
 */
MonitorSettings.prototype['request_basic_auth_username'] = undefined;

/**
 * @member {String} request_basic_auth_password
 */
MonitorSettings.prototype['request_basic_auth_password'] = undefined;

/**
 * @member {Array.<String>} request_headers
 */
MonitorSettings.prototype['request_headers'] = undefined;

/**
 * @member {Number} response_status_code
 */
MonitorSettings.prototype['response_status_code'] = undefined;

/**
 * @member {String} response_body
 */
MonitorSettings.prototype['response_body'] = undefined;

/**
 * @member {Array.<String>} response_headers
 */
MonitorSettings.prototype['response_headers'] = undefined;






export default MonitorSettings;

