/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MonitorNotifications model module.
 * @module model/MonitorNotifications
 * @version 1.0.0
 */
class MonitorNotifications {
    /**
     * Constructs a new <code>MonitorNotifications</code>.
     * @alias module:model/MonitorNotifications
     */
    constructor() { 
        
        MonitorNotifications.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MonitorNotifications</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MonitorNotifications} obj Optional instance to populate.
     * @return {module:model/MonitorNotifications} The populated <code>MonitorNotifications</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MonitorNotifications();

            if (data.hasOwnProperty('email_is_enabled')) {
                obj['email_is_enabled'] = ApiClient.convertToType(data['email_is_enabled'], 'Number');
            }
            if (data.hasOwnProperty('webhook')) {
                obj['webhook'] = ApiClient.convertToType(data['webhook'], 'String');
            }
            if (data.hasOwnProperty('slack')) {
                obj['slack'] = ApiClient.convertToType(data['slack'], 'String');
            }
            if (data.hasOwnProperty('twilio')) {
                obj['twilio'] = ApiClient.convertToType(data['twilio'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MonitorNotifications</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MonitorNotifications</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['webhook'] && !(typeof data['webhook'] === 'string' || data['webhook'] instanceof String)) {
            throw new Error("Expected the field `webhook` to be a primitive type in the JSON string but got " + data['webhook']);
        }
        // ensure the json data is a string
        if (data['slack'] && !(typeof data['slack'] === 'string' || data['slack'] instanceof String)) {
            throw new Error("Expected the field `slack` to be a primitive type in the JSON string but got " + data['slack']);
        }
        // ensure the json data is a string
        if (data['twilio'] && !(typeof data['twilio'] === 'string' || data['twilio'] instanceof String)) {
            throw new Error("Expected the field `twilio` to be a primitive type in the JSON string but got " + data['twilio']);
        }

        return true;
    }


}



/**
 * @member {Number} email_is_enabled
 */
MonitorNotifications.prototype['email_is_enabled'] = undefined;

/**
 * @member {String} webhook
 */
MonitorNotifications.prototype['webhook'] = undefined;

/**
 * @member {String} slack
 */
MonitorNotifications.prototype['slack'] = undefined;

/**
 * @member {String} twilio
 */
MonitorNotifications.prototype['twilio'] = undefined;






export default MonitorNotifications;

