/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NotificationHandlerSettings from './NotificationHandlerSettings';

/**
 * The NotificationHandler model module.
 * @module model/NotificationHandler
 * @version 1.0.0
 */
class NotificationHandler {
    /**
     * Constructs a new <code>NotificationHandler</code>.
     * @alias module:model/NotificationHandler
     */
    constructor() { 
        
        NotificationHandler.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NotificationHandler</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NotificationHandler} obj Optional instance to populate.
     * @return {module:model/NotificationHandler} The populated <code>NotificationHandler</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationHandler();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = NotificationHandlerSettings.constructFromObject(data['settings']);
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'String');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NotificationHandler</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NotificationHandler</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `settings`
        if (data['settings']) { // data not null
          NotificationHandlerSettings.validateJSON(data['settings']);
        }
        // ensure the json data is a string
        if (data['last_datetime'] && !(typeof data['last_datetime'] === 'string' || data['last_datetime'] instanceof String)) {
            throw new Error("Expected the field `last_datetime` to be a primitive type in the JSON string but got " + data['last_datetime']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
NotificationHandler.prototype['id'] = undefined;

/**
 * @member {module:model/NotificationHandler.TypeEnum} type
 */
NotificationHandler.prototype['type'] = undefined;

/**
 * @member {String} name
 */
NotificationHandler.prototype['name'] = undefined;

/**
 * @member {module:model/NotificationHandlerSettings} settings
 */
NotificationHandler.prototype['settings'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
NotificationHandler.prototype['is_enabled'] = undefined;

/**
 * @member {String} last_datetime
 */
NotificationHandler.prototype['last_datetime'] = undefined;

/**
 * @member {Date} datetime
 */
NotificationHandler.prototype['datetime'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
NotificationHandler['TypeEnum'] = {

    /**
     * value: "email"
     * @const
     */
    "email": "email",

    /**
     * value: "webhook"
     * @const
     */
    "webhook": "webhook",

    /**
     * value: "squadcast"
     * @const
     */
    "squadcast": "squadcast",

    /**
     * value: "googlechat"
     * @const
     */
    "googlechat": "googlechat",

    /**
     * value: "slack"
     * @const
     */
    "slack": "slack",

    /**
     * value: "discord"
     * @const
     */
    "discord": "discord",

    /**
     * value: "telegram"
     * @const
     */
    "telegram": "telegram",

    /**
     * value: "microsoft_teams"
     * @const
     */
    "microsoft_teams": "microsoft_teams"
};



export default NotificationHandler;

