/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServerMonitorSettings from './ServerMonitorSettings';

/**
 * The ServerMonitor model module.
 * @module model/ServerMonitor
 * @version 1.0.0
 */
class ServerMonitor {
    /**
     * Constructs a new <code>ServerMonitor</code>.
     * @alias module:model/ServerMonitor
     */
    constructor() { 
        
        ServerMonitor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServerMonitor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServerMonitor} obj Optional instance to populate.
     * @return {module:model/ServerMonitor} The populated <code>ServerMonitor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerMonitor();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = ServerMonitorSettings.constructFromObject(data['settings']);
            }
            if (data.hasOwnProperty('cpu_usage')) {
                obj['cpu_usage'] = ApiClient.convertToType(data['cpu_usage'], 'Number');
            }
            if (data.hasOwnProperty('ram_usage')) {
                obj['ram_usage'] = ApiClient.convertToType(data['ram_usage'], 'Number');
            }
            if (data.hasOwnProperty('disk_usage')) {
                obj['disk_usage'] = ApiClient.convertToType(data['disk_usage'], 'Number');
            }
            if (data.hasOwnProperty('cpu_load_1')) {
                obj['cpu_load_1'] = ApiClient.convertToType(data['cpu_load_1'], 'Number');
            }
            if (data.hasOwnProperty('cpu_load_5')) {
                obj['cpu_load_5'] = ApiClient.convertToType(data['cpu_load_5'], 'Number');
            }
            if (data.hasOwnProperty('cpu_load_15')) {
                obj['cpu_load_15'] = ApiClient.convertToType(data['cpu_load_15'], 'Number');
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('total_logs')) {
                obj['total_logs'] = ApiClient.convertToType(data['total_logs'], 'Number');
            }
            if (data.hasOwnProperty('last_log_datetime')) {
                obj['last_log_datetime'] = ApiClient.convertToType(data['last_log_datetime'], 'Date');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServerMonitor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServerMonitor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        // validate the optional field `settings`
        if (data['settings']) { // data not null
          ServerMonitorSettings.validateJSON(data['settings']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ServerMonitor.prototype['id'] = undefined;

/**
 * @member {Number} project_id
 */
ServerMonitor.prototype['project_id'] = undefined;

/**
 * @member {String} name
 */
ServerMonitor.prototype['name'] = undefined;

/**
 * @member {String} target
 */
ServerMonitor.prototype['target'] = undefined;

/**
 * @member {module:model/ServerMonitorSettings} settings
 */
ServerMonitor.prototype['settings'] = undefined;

/**
 * @member {Number} cpu_usage
 */
ServerMonitor.prototype['cpu_usage'] = undefined;

/**
 * @member {Number} ram_usage
 */
ServerMonitor.prototype['ram_usage'] = undefined;

/**
 * @member {Number} disk_usage
 */
ServerMonitor.prototype['disk_usage'] = undefined;

/**
 * @member {Number} cpu_load_1
 */
ServerMonitor.prototype['cpu_load_1'] = undefined;

/**
 * @member {Number} cpu_load_5
 */
ServerMonitor.prototype['cpu_load_5'] = undefined;

/**
 * @member {Number} cpu_load_15
 */
ServerMonitor.prototype['cpu_load_15'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
ServerMonitor.prototype['is_enabled'] = undefined;

/**
 * @member {Number} total_logs
 */
ServerMonitor.prototype['total_logs'] = undefined;

/**
 * @member {Date} last_log_datetime
 */
ServerMonitor.prototype['last_log_datetime'] = undefined;

/**
 * @member {Date} datetime
 */
ServerMonitor.prototype['datetime'] = undefined;

/**
 * @member {Date} last_datetime
 */
ServerMonitor.prototype['last_datetime'] = undefined;






export default ServerMonitor;

