/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StatusPageStatistic model module.
 * @module model/StatusPageStatistic
 * @version 1.0.0
 */
class StatusPageStatistic {
    /**
     * Constructs a new <code>StatusPageStatistic</code>.
     * @alias module:model/StatusPageStatistic
     */
    constructor() { 
        
        StatusPageStatistic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatusPageStatistic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatusPageStatistic} obj Optional instance to populate.
     * @return {module:model/StatusPageStatistic} The populated <code>StatusPageStatistic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatusPageStatistic();

            if (data.hasOwnProperty('pageviews')) {
                obj['pageviews'] = ApiClient.convertToType(data['pageviews'], 'Number');
            }
            if (data.hasOwnProperty('visitors')) {
                obj['visitors'] = ApiClient.convertToType(data['visitors'], 'Number');
            }
            if (data.hasOwnProperty('formatted_date')) {
                obj['formatted_date'] = ApiClient.convertToType(data['formatted_date'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatusPageStatistic</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatusPageStatistic</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['formatted_date'] && !(typeof data['formatted_date'] === 'string' || data['formatted_date'] instanceof String)) {
            throw new Error("Expected the field `formatted_date` to be a primitive type in the JSON string but got " + data['formatted_date']);
        }

        return true;
    }


}



/**
 * @member {Number} pageviews
 */
StatusPageStatistic.prototype['pageviews'] = undefined;

/**
 * @member {Number} visitors
 */
StatusPageStatistic.prototype['visitors'] = undefined;

/**
 * @member {String} formatted_date
 */
StatusPageStatistic.prototype['formatted_date'] = undefined;






export default StatusPageStatistic;

