/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StatusPageSocials model module.
 * @module model/StatusPageSocials
 * @version 1.0.0
 */
class StatusPageSocials {
    /**
     * Constructs a new <code>StatusPageSocials</code>.
     * @alias module:model/StatusPageSocials
     */
    constructor() { 
        
        StatusPageSocials.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatusPageSocials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatusPageSocials} obj Optional instance to populate.
     * @return {module:model/StatusPageSocials} The populated <code>StatusPageSocials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatusPageSocials();

            if (data.hasOwnProperty('facebook')) {
                obj['facebook'] = ApiClient.convertToType(data['facebook'], 'String');
            }
            if (data.hasOwnProperty('instagram')) {
                obj['instagram'] = ApiClient.convertToType(data['instagram'], 'String');
            }
            if (data.hasOwnProperty('twitter')) {
                obj['twitter'] = ApiClient.convertToType(data['twitter'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatusPageSocials</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatusPageSocials</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['facebook'] && !(typeof data['facebook'] === 'string' || data['facebook'] instanceof String)) {
            throw new Error("Expected the field `facebook` to be a primitive type in the JSON string but got " + data['facebook']);
        }
        // ensure the json data is a string
        if (data['instagram'] && !(typeof data['instagram'] === 'string' || data['instagram'] instanceof String)) {
            throw new Error("Expected the field `instagram` to be a primitive type in the JSON string but got " + data['instagram']);
        }
        // ensure the json data is a string
        if (data['twitter'] && !(typeof data['twitter'] === 'string' || data['twitter'] instanceof String)) {
            throw new Error("Expected the field `twitter` to be a primitive type in the JSON string but got " + data['twitter']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['website'] && !(typeof data['website'] === 'string' || data['website'] instanceof String)) {
            throw new Error("Expected the field `website` to be a primitive type in the JSON string but got " + data['website']);
        }

        return true;
    }


}



/**
 * @member {String} facebook
 */
StatusPageSocials.prototype['facebook'] = undefined;

/**
 * @member {String} instagram
 */
StatusPageSocials.prototype['instagram'] = undefined;

/**
 * @member {String} twitter
 */
StatusPageSocials.prototype['twitter'] = undefined;

/**
 * @member {String} email
 */
StatusPageSocials.prototype['email'] = undefined;

/**
 * @member {String} website
 */
StatusPageSocials.prototype['website'] = undefined;






export default StatusPageSocials;

