/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StatusPageSocials from './StatusPageSocials';

/**
 * The StatusPage model module.
 * @module model/StatusPage
 * @version 1.0.0
 */
class StatusPage {
    /**
     * Constructs a new <code>StatusPage</code>.
     * @alias module:model/StatusPage
     */
    constructor() { 
        
        StatusPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatusPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatusPage} obj Optional instance to populate.
     * @return {module:model/StatusPage} The populated <code>StatusPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatusPage();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('domain_id')) {
                obj['domain_id'] = ApiClient.convertToType(data['domain_id'], 'Number');
            }
            if (data.hasOwnProperty('monitors_ids')) {
                obj['monitors_ids'] = ApiClient.convertToType(data['monitors_ids'], ['Number']);
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('full_url')) {
                obj['full_url'] = ApiClient.convertToType(data['full_url'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('socials')) {
                obj['socials'] = StatusPageSocials.constructFromObject(data['socials']);
            }
            if (data.hasOwnProperty('logo_url')) {
                obj['logo_url'] = ApiClient.convertToType(data['logo_url'], 'String');
            }
            if (data.hasOwnProperty('favicon_url')) {
                obj['favicon_url'] = ApiClient.convertToType(data['favicon_url'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'Boolean');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('custom_js')) {
                obj['custom_js'] = ApiClient.convertToType(data['custom_js'], 'String');
            }
            if (data.hasOwnProperty('custom_css')) {
                obj['custom_css'] = ApiClient.convertToType(data['custom_css'], 'String');
            }
            if (data.hasOwnProperty('pageviews')) {
                obj['pageviews'] = ApiClient.convertToType(data['pageviews'], 'Number');
            }
            if (data.hasOwnProperty('is_se_visible')) {
                obj['is_se_visible'] = ApiClient.convertToType(data['is_se_visible'], 'Boolean');
            }
            if (data.hasOwnProperty('is_removed_branding')) {
                obj['is_removed_branding'] = ApiClient.convertToType(data['is_removed_branding'], 'Boolean');
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatusPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatusPage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['monitors_ids'])) {
            throw new Error("Expected the field `monitors_ids` to be an array in the JSON data but got " + data['monitors_ids']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['full_url'] && !(typeof data['full_url'] === 'string' || data['full_url'] instanceof String)) {
            throw new Error("Expected the field `full_url` to be a primitive type in the JSON string but got " + data['full_url']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `socials`
        if (data['socials']) { // data not null
          StatusPageSocials.validateJSON(data['socials']);
        }
        // ensure the json data is a string
        if (data['logo_url'] && !(typeof data['logo_url'] === 'string' || data['logo_url'] instanceof String)) {
            throw new Error("Expected the field `logo_url` to be a primitive type in the JSON string but got " + data['logo_url']);
        }
        // ensure the json data is a string
        if (data['favicon_url'] && !(typeof data['favicon_url'] === 'string' || data['favicon_url'] instanceof String)) {
            throw new Error("Expected the field `favicon_url` to be a primitive type in the JSON string but got " + data['favicon_url']);
        }
        // ensure the json data is a string
        if (data['timezone'] && !(typeof data['timezone'] === 'string' || data['timezone'] instanceof String)) {
            throw new Error("Expected the field `timezone` to be a primitive type in the JSON string but got " + data['timezone']);
        }
        // ensure the json data is a string
        if (data['custom_js'] && !(typeof data['custom_js'] === 'string' || data['custom_js'] instanceof String)) {
            throw new Error("Expected the field `custom_js` to be a primitive type in the JSON string but got " + data['custom_js']);
        }
        // ensure the json data is a string
        if (data['custom_css'] && !(typeof data['custom_css'] === 'string' || data['custom_css'] instanceof String)) {
            throw new Error("Expected the field `custom_css` to be a primitive type in the JSON string but got " + data['custom_css']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
StatusPage.prototype['id'] = undefined;

/**
 * @member {Number} domain_id
 */
StatusPage.prototype['domain_id'] = undefined;

/**
 * @member {Array.<Number>} monitors_ids
 */
StatusPage.prototype['monitors_ids'] = undefined;

/**
 * @member {Number} project_id
 */
StatusPage.prototype['project_id'] = undefined;

/**
 * @member {String} url
 */
StatusPage.prototype['url'] = undefined;

/**
 * @member {String} full_url
 */
StatusPage.prototype['full_url'] = undefined;

/**
 * @member {String} name
 */
StatusPage.prototype['name'] = undefined;

/**
 * @member {String} description
 */
StatusPage.prototype['description'] = undefined;

/**
 * @member {module:model/StatusPageSocials} socials
 */
StatusPage.prototype['socials'] = undefined;

/**
 * @member {String} logo_url
 */
StatusPage.prototype['logo_url'] = undefined;

/**
 * @member {String} favicon_url
 */
StatusPage.prototype['favicon_url'] = undefined;

/**
 * @member {Boolean} password
 */
StatusPage.prototype['password'] = undefined;

/**
 * @member {String} timezone
 */
StatusPage.prototype['timezone'] = undefined;

/**
 * @member {String} custom_js
 */
StatusPage.prototype['custom_js'] = undefined;

/**
 * @member {String} custom_css
 */
StatusPage.prototype['custom_css'] = undefined;

/**
 * @member {Number} pageviews
 */
StatusPage.prototype['pageviews'] = undefined;

/**
 * @member {Boolean} is_se_visible
 */
StatusPage.prototype['is_se_visible'] = undefined;

/**
 * @member {Boolean} is_removed_branding
 */
StatusPage.prototype['is_removed_branding'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
StatusPage.prototype['is_enabled'] = undefined;

/**
 * @member {Date} datetime
 */
StatusPage.prototype['datetime'] = undefined;






export default StatusPage;

