/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamMemberAccess from './TeamMemberAccess';

/**
 * The TeamMember model module.
 * @module model/TeamMember
 * @version 1.0.0
 */
class TeamMember {
    /**
     * Constructs a new <code>TeamMember</code>.
     * @alias module:model/TeamMember
     */
    constructor() { 
        
        TeamMember.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamMember</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamMember} obj Optional instance to populate.
     * @return {module:model/TeamMember} The populated <code>TeamMember</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamMember();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('access')) {
                obj['access'] = TeamMemberAccess.constructFromObject(data['access']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'Date');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamMember</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamMember</code>.
     */
    static validateJSON(data) {
        // validate the optional field `access`
        if (data['access']) { // data not null
          TeamMemberAccess.validateJSON(data['access']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TeamMember.prototype['id'] = undefined;

/**
 * @member {module:model/TeamMemberAccess} access
 */
TeamMember.prototype['access'] = undefined;

/**
 * @member {Number} status
 */
TeamMember.prototype['status'] = undefined;

/**
 * @member {Date} last_datetime
 */
TeamMember.prototype['last_datetime'] = undefined;

/**
 * @member {Date} datetime
 */
TeamMember.prototype['datetime'] = undefined;

/**
 * @member {Number} team_id
 */
TeamMember.prototype['team_id'] = undefined;

/**
 * @member {String} name
 */
TeamMember.prototype['name'] = undefined;






export default TeamMember;

