/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamMember from './TeamMember';

/**
 * The Team model module.
 * @module model/Team
 * @version 1.0.0
 */
class Team {
    /**
     * Constructs a new <code>Team</code>.
     * @alias module:model/Team
     */
    constructor() { 
        
        Team.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Team</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Team} obj Optional instance to populate.
     * @return {module:model/Team} The populated <code>Team</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Team();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('team_members')) {
                obj['team_members'] = ApiClient.convertToType(data['team_members'], [TeamMember]);
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'String');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Team</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Team</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['team_members']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['team_members'])) {
                throw new Error("Expected the field `team_members` to be an array in the JSON data but got " + data['team_members']);
            }
            // validate the optional field `team_members` (array)
            for (const item of data['team_members']) {
                TeamMember.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['last_datetime'] && !(typeof data['last_datetime'] === 'string' || data['last_datetime'] instanceof String)) {
            throw new Error("Expected the field `last_datetime` to be a primitive type in the JSON string but got " + data['last_datetime']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Team.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Team.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/TeamMember>} team_members
 */
Team.prototype['team_members'] = undefined;

/**
 * @member {String} last_datetime
 */
Team.prototype['last_datetime'] = undefined;

/**
 * @member {Date} datetime
 */
Team.prototype['datetime'] = undefined;






export default Team;

