/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamMemberAccess model module.
 * @module model/TeamMemberAccess
 * @version 1.0.0
 */
class TeamMemberAccess {
    /**
     * Constructs a new <code>TeamMemberAccess</code>.
     * @alias module:model/TeamMemberAccess
     */
    constructor() { 
        
        TeamMemberAccess.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamMemberAccess</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamMemberAccess} obj Optional instance to populate.
     * @return {module:model/TeamMemberAccess} The populated <code>TeamMemberAccess</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamMemberAccess();

            if (data.hasOwnProperty('read')) {
                obj['read'] = ApiClient.convertToType(data['read'], 'Boolean');
            }
            if (data.hasOwnProperty('create')) {
                obj['create'] = ApiClient.convertToType(data['create'], 'Boolean');
            }
            if (data.hasOwnProperty('update')) {
                obj['update'] = ApiClient.convertToType(data['update'], 'Boolean');
            }
            if (data.hasOwnProperty('delete')) {
                obj['delete'] = ApiClient.convertToType(data['delete'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamMemberAccess</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamMemberAccess</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} read
 */
TeamMemberAccess.prototype['read'] = undefined;

/**
 * @member {Boolean} create
 */
TeamMemberAccess.prototype['create'] = undefined;

/**
 * @member {Boolean} update
 */
TeamMemberAccess.prototype['update'] = undefined;

/**
 * @member {Boolean} delete
 */
TeamMemberAccess.prototype['delete'] = undefined;






export default TeamMemberAccess;

