/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamMemberAccess from './TeamMemberAccess';

/**
 * The TeamMemberDetailed model module.
 * @module model/TeamMemberDetailed
 * @version 1.0.0
 */
class TeamMemberDetailed {
    /**
     * Constructs a new <code>TeamMemberDetailed</code>.
     * @alias module:model/TeamMemberDetailed
     */
    constructor() { 
        
        TeamMemberDetailed.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamMemberDetailed</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamMemberDetailed} obj Optional instance to populate.
     * @return {module:model/TeamMemberDetailed} The populated <code>TeamMemberDetailed</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamMemberDetailed();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
            if (data.hasOwnProperty('user_email')) {
                obj['user_email'] = ApiClient.convertToType(data['user_email'], 'String');
            }
            if (data.hasOwnProperty('access')) {
                obj['access'] = TeamMemberAccess.constructFromObject(data['access']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'Date');
            }
            if (data.hasOwnProperty('last_datetime')) {
                obj['last_datetime'] = ApiClient.convertToType(data['last_datetime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TeamMemberDetailed</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TeamMemberDetailed</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['user_email'] && !(typeof data['user_email'] === 'string' || data['user_email'] instanceof String)) {
            throw new Error("Expected the field `user_email` to be a primitive type in the JSON string but got " + data['user_email']);
        }
        // validate the optional field `access`
        if (data['access']) { // data not null
          TeamMemberAccess.validateJSON(data['access']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TeamMemberDetailed.prototype['id'] = undefined;

/**
 * @member {Number} team_id
 */
TeamMemberDetailed.prototype['team_id'] = undefined;

/**
 * @member {String} user_email
 */
TeamMemberDetailed.prototype['user_email'] = undefined;

/**
 * @member {module:model/TeamMemberAccess} access
 */
TeamMemberDetailed.prototype['access'] = undefined;

/**
 * @member {Number} status
 */
TeamMemberDetailed.prototype['status'] = undefined;

/**
 * @member {Date} datetime
 */
TeamMemberDetailed.prototype['datetime'] = undefined;

/**
 * @member {Date} last_datetime
 */
TeamMemberDetailed.prototype['last_datetime'] = undefined;






export default TeamMemberDetailed;

