/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetAllCustomDomains200Response from '../model/GetAllCustomDomains200Response';
import GetCustomDomain200Response from '../model/GetCustomDomain200Response';
import MonitorsPost201Response from '../model/MonitorsPost201Response';

/**
* CustomDomains service.
* @module api/CustomDomainsApi
* @version 1.0.0
*/
export default class CustomDomainsApi {

    /**
    * Constructs a new CustomDomainsApi. 
    * @alias module:api/CustomDomainsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createCustomDomain operation.
     * @callback module:api/CustomDomainsApi~createCustomDomainCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create custom domain
     * Creates a new custom domain.
     * @param {String} host 
     * @param {Object} opts Optional parameters
     * @param {String} [customIndexUrl] 
     * @param {String} [customNotFoundUrl] 
     * @param {module:api/CustomDomainsApi~createCustomDomainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    createCustomDomain(host, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'host' is set
      if (host === undefined || host === null) {
        throw new Error("Missing the required parameter 'host' when calling createCustomDomain");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'host': host,
        'custom_index_url': opts['customIndexUrl'],
        'custom_not_found_url': opts['customNotFoundUrl']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/domains', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteCustomDomain operation.
     * @callback module:api/CustomDomainsApi~deleteCustomDomainCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete custom domain
     * Deletes a custom domain.
     * @param {Number} domainId 
     * @param {module:api/CustomDomainsApi~deleteCustomDomainCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteCustomDomain(domainId, callback) {
      let postBody = null;
      // verify the required parameter 'domainId' is set
      if (domainId === undefined || domainId === null) {
        throw new Error("Missing the required parameter 'domainId' when calling deleteCustomDomain");
      }

      let pathParams = {
        'domain_id': domainId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/domains/{domain_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllCustomDomains operation.
     * @callback module:api/CustomDomainsApi~getAllCustomDomainsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAllCustomDomains200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all custom domains
     * Returns a paginated list of custom domains.
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/CustomDomainsApi~getAllCustomDomainsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAllCustomDomains200Response}
     */
    getAllCustomDomains(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAllCustomDomains200Response;
      return this.apiClient.callApi(
        '/domains', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCustomDomain operation.
     * @callback module:api/CustomDomainsApi~getCustomDomainCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetCustomDomain200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one custom domain
     * Returns details of a specific custom domain.
     * @param {Number} domainId 
     * @param {module:api/CustomDomainsApi~getCustomDomainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetCustomDomain200Response}
     */
    getCustomDomain(domainId, callback) {
      let postBody = null;
      // verify the required parameter 'domainId' is set
      if (domainId === undefined || domainId === null) {
        throw new Error("Missing the required parameter 'domainId' when calling getCustomDomain");
      }

      let pathParams = {
        'domain_id': domainId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCustomDomain200Response;
      return this.apiClient.callApi(
        '/domains/{domain_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCustomDomain operation.
     * @callback module:api/CustomDomainsApi~updateCustomDomainCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update custom domain
     * Updates an existing custom domain.
     * @param {Number} domainId 
     * @param {Object} opts Optional parameters
     * @param {String} [host] 
     * @param {String} [customIndexUrl] 
     * @param {String} [customNotFoundUrl] 
     * @param {module:api/CustomDomainsApi~updateCustomDomainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    updateCustomDomain(domainId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'domainId' is set
      if (domainId === undefined || domainId === null) {
        throw new Error("Missing the required parameter 'domainId' when calling updateCustomDomain");
      }

      let pathParams = {
        'domain_id': domainId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'host': opts['host'],
        'custom_index_url': opts['customIndexUrl'],
        'custom_not_found_url': opts['customNotFoundUrl']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/domains/{domain_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
