/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeleteDNSMonitor200Response from '../model/DeleteDNSMonitor200Response';
import GetAllDNSMonitors200Response from '../model/GetAllDNSMonitors200Response';
import GetDNSMonitor200Response from '../model/GetDNSMonitor200Response';

/**
* DNSMonitors service.
* @module api/DNSMonitorsApi
* @version 1.0.0
*/
export default class DNSMonitorsApi {

    /**
    * Constructs a new DNSMonitorsApi. 
    * @alias module:api/DNSMonitorsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteDNSMonitor operation.
     * @callback module:api/DNSMonitorsApi~deleteDNSMonitorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteDNSMonitor200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete DNS monitor
     * Deletes a DNS monitor.
     * @param {Number} id 
     * @param {module:api/DNSMonitorsApi~deleteDNSMonitorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteDNSMonitor200Response}
     */
    deleteDNSMonitor(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteDNSMonitor");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeleteDNSMonitor200Response;
      return this.apiClient.callApi(
        '/dns-monitors/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllDNSMonitors operation.
     * @callback module:api/DNSMonitorsApi~getAllDNSMonitorsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAllDNSMonitors200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all DNS monitors
     * Returns a paginated list of DNS monitors.
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/DNSMonitorsApi~getAllDNSMonitorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAllDNSMonitors200Response}
     */
    getAllDNSMonitors(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAllDNSMonitors200Response;
      return this.apiClient.callApi(
        '/dns-monitors', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDNSMonitor operation.
     * @callback module:api/DNSMonitorsApi~getDNSMonitorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetDNSMonitor200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one DNS monitor
     * Returns details of a specific DNS monitor.
     * @param {Number} id 
     * @param {module:api/DNSMonitorsApi~getDNSMonitorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetDNSMonitor200Response}
     */
    getDNSMonitor(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getDNSMonitor");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetDNSMonitor200Response;
      return this.apiClient.callApi(
        '/dns-monitors/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
