/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DomainNamesDomainNameIdGet200Response from '../model/DomainNamesDomainNameIdGet200Response';
import DomainNamesGet200Response from '../model/DomainNamesGet200Response';
import MonitorsPost201Response from '../model/MonitorsPost201Response';

/**
* DomainMonitors service.
* @module api/DomainMonitorsApi
* @version 1.0.0
*/
export default class DomainMonitorsApi {

    /**
    * Constructs a new DomainMonitorsApi. 
    * @alias module:api/DomainMonitorsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the domainNamesDomainNameIdDelete operation.
     * @callback module:api/DomainMonitorsApi~domainNamesDomainNameIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete domain name monitor
     * @param {Number} domainNameId 
     * @param {module:api/DomainMonitorsApi~domainNamesDomainNameIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    domainNamesDomainNameIdDelete(domainNameId, callback) {
      let postBody = null;
      // verify the required parameter 'domainNameId' is set
      if (domainNameId === undefined || domainNameId === null) {
        throw new Error("Missing the required parameter 'domainNameId' when calling domainNamesDomainNameIdDelete");
      }

      let pathParams = {
        'domain_name_id': domainNameId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/domain-names/{domain_name_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the domainNamesDomainNameIdGet operation.
     * @callback module:api/DomainMonitorsApi~domainNamesDomainNameIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DomainNamesDomainNameIdGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one domain name monitor
     * @param {Number} domainNameId 
     * @param {module:api/DomainMonitorsApi~domainNamesDomainNameIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DomainNamesDomainNameIdGet200Response}
     */
    domainNamesDomainNameIdGet(domainNameId, callback) {
      let postBody = null;
      // verify the required parameter 'domainNameId' is set
      if (domainNameId === undefined || domainNameId === null) {
        throw new Error("Missing the required parameter 'domainNameId' when calling domainNamesDomainNameIdGet");
      }

      let pathParams = {
        'domain_name_id': domainNameId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DomainNamesDomainNameIdGet200Response;
      return this.apiClient.callApi(
        '/domain-names/{domain_name_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the domainNamesDomainNameIdPost operation.
     * @callback module:api/DomainMonitorsApi~domainNamesDomainNameIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update domain name monitor
     * @param {Number} domainNameId 
     * @param {Object} opts Optional parameters
     * @param {String} [name] 
     * @param {String} [target] 
     * @param {Number} [projectId] 
     * @param {Array.<Number>} [whoisNotifications] 
     * @param {module:model/Number} [whoisNotificationsTiming] 
     * @param {Array.<Number>} [sslNotifications] 
     * @param {module:model/Number} [sslNotificationsTiming] 
     * @param {Boolean} [isEnabled] 
     * @param {module:api/DomainMonitorsApi~domainNamesDomainNameIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    domainNamesDomainNameIdPost(domainNameId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'domainNameId' is set
      if (domainNameId === undefined || domainNameId === null) {
        throw new Error("Missing the required parameter 'domainNameId' when calling domainNamesDomainNameIdPost");
      }

      let pathParams = {
        'domain_name_id': domainNameId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': opts['name'],
        'target': opts['target'],
        'project_id': opts['projectId'],
        'whois_notifications': this.apiClient.buildCollectionParam(opts['whoisNotifications'], 'csv'),
        'whois_notifications_timing': opts['whoisNotificationsTiming'],
        'ssl_notifications': this.apiClient.buildCollectionParam(opts['sslNotifications'], 'csv'),
        'ssl_notifications_timing': opts['sslNotificationsTiming'],
        'is_enabled': opts['isEnabled']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/domain-names/{domain_name_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the domainNamesGet operation.
     * @callback module:api/DomainMonitorsApi~domainNamesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DomainNamesGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all domain name monitors
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/DomainMonitorsApi~domainNamesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DomainNamesGet200Response}
     */
    domainNamesGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DomainNamesGet200Response;
      return this.apiClient.callApi(
        '/domain-names', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the domainNamesPost operation.
     * @callback module:api/DomainMonitorsApi~domainNamesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create domain name monitor
     * @param {String} name 
     * @param {String} target 
     * @param {Object} opts Optional parameters
     * @param {Number} [projectId] 
     * @param {Array.<Number>} [whoisNotifications] 
     * @param {module:model/Number} [whoisNotificationsTiming] 
     * @param {Array.<Number>} [sslNotifications] 
     * @param {module:model/Number} [sslNotificationsTiming] 
     * @param {Boolean} [isEnabled] 
     * @param {module:api/DomainMonitorsApi~domainNamesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    domainNamesPost(name, target, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling domainNamesPost");
      }
      // verify the required parameter 'target' is set
      if (target === undefined || target === null) {
        throw new Error("Missing the required parameter 'target' when calling domainNamesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'target': target,
        'project_id': opts['projectId'],
        'whois_notifications': this.apiClient.buildCollectionParam(opts['whoisNotifications'], 'csv'),
        'whois_notifications_timing': opts['whoisNotificationsTiming'],
        'ssl_notifications': this.apiClient.buildCollectionParam(opts['sslNotifications'], 'csv'),
        'ssl_notifications_timing': opts['sslNotificationsTiming'],
        'is_enabled': opts['isEnabled']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/domain-names', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
