/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HeartbeatsGet200Response from '../model/HeartbeatsGet200Response';
import HeartbeatsHeartbeatIdGet200Response from '../model/HeartbeatsHeartbeatIdGet200Response';
import MonitorsPost201Response from '../model/MonitorsPost201Response';

/**
* HeartbeatMonitors service.
* @module api/HeartbeatMonitorsApi
* @version 1.0.0
*/
export default class HeartbeatMonitorsApi {

    /**
    * Constructs a new HeartbeatMonitorsApi. 
    * @alias module:api/HeartbeatMonitorsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the heartbeatsGet operation.
     * @callback module:api/HeartbeatMonitorsApi~heartbeatsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HeartbeatsGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all heartbeat monitors
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/HeartbeatMonitorsApi~heartbeatsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HeartbeatsGet200Response}
     */
    heartbeatsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HeartbeatsGet200Response;
      return this.apiClient.callApi(
        '/heartbeats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the heartbeatsHeartbeatIdDelete operation.
     * @callback module:api/HeartbeatMonitorsApi~heartbeatsHeartbeatIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete heartbeat monitor
     * @param {Number} heartbeatId 
     * @param {module:api/HeartbeatMonitorsApi~heartbeatsHeartbeatIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    heartbeatsHeartbeatIdDelete(heartbeatId, callback) {
      let postBody = null;
      // verify the required parameter 'heartbeatId' is set
      if (heartbeatId === undefined || heartbeatId === null) {
        throw new Error("Missing the required parameter 'heartbeatId' when calling heartbeatsHeartbeatIdDelete");
      }

      let pathParams = {
        'heartbeat_id': heartbeatId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/heartbeats/{heartbeat_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the heartbeatsHeartbeatIdGet operation.
     * @callback module:api/HeartbeatMonitorsApi~heartbeatsHeartbeatIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HeartbeatsHeartbeatIdGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one heartbeat monitor
     * @param {Number} heartbeatId 
     * @param {module:api/HeartbeatMonitorsApi~heartbeatsHeartbeatIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HeartbeatsHeartbeatIdGet200Response}
     */
    heartbeatsHeartbeatIdGet(heartbeatId, callback) {
      let postBody = null;
      // verify the required parameter 'heartbeatId' is set
      if (heartbeatId === undefined || heartbeatId === null) {
        throw new Error("Missing the required parameter 'heartbeatId' when calling heartbeatsHeartbeatIdGet");
      }

      let pathParams = {
        'heartbeat_id': heartbeatId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HeartbeatsHeartbeatIdGet200Response;
      return this.apiClient.callApi(
        '/heartbeats/{heartbeat_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the heartbeatsHeartbeatIdPost operation.
     * @callback module:api/HeartbeatMonitorsApi~heartbeatsHeartbeatIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update heartbeat monitor
     * @param {Number} heartbeatId 
     * @param {Object} opts Optional parameters
     * @param {String} [name] 
     * @param {Number} [runInterval] 
     * @param {module:model/String} [runIntervalType] 
     * @param {Number} [runIntervalGrace] 
     * @param {module:model/String} [runIntervalGraceType] 
     * @param {Array.<Number>} [isOkNotifications] 
     * @param {Boolean} [isEnabled] 
     * @param {module:api/HeartbeatMonitorsApi~heartbeatsHeartbeatIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    heartbeatsHeartbeatIdPost(heartbeatId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'heartbeatId' is set
      if (heartbeatId === undefined || heartbeatId === null) {
        throw new Error("Missing the required parameter 'heartbeatId' when calling heartbeatsHeartbeatIdPost");
      }

      let pathParams = {
        'heartbeat_id': heartbeatId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': opts['name'],
        'run_interval': opts['runInterval'],
        'run_interval_type': opts['runIntervalType'],
        'run_interval_grace': opts['runIntervalGrace'],
        'run_interval_grace_type': opts['runIntervalGraceType'],
        'is_ok_notifications': this.apiClient.buildCollectionParam(opts['isOkNotifications'], 'csv'),
        'is_enabled': opts['isEnabled']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/heartbeats/{heartbeat_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the heartbeatsPost operation.
     * @callback module:api/HeartbeatMonitorsApi~heartbeatsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create heartbeat monitor
     * @param {String} name 
     * @param {Object} opts Optional parameters
     * @param {Number} [runInterval] 
     * @param {module:model/String} [runIntervalType] 
     * @param {Number} [runIntervalGrace] 
     * @param {module:model/String} [runIntervalGraceType] 
     * @param {Array.<Number>} [isOkNotifications] 
     * @param {Boolean} [isEnabled] 
     * @param {module:api/HeartbeatMonitorsApi~heartbeatsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    heartbeatsPost(name, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling heartbeatsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'run_interval': opts['runInterval'],
        'run_interval_type': opts['runIntervalType'],
        'run_interval_grace': opts['runIntervalGrace'],
        'run_interval_grace_type': opts['runIntervalGraceType'],
        'is_ok_notifications': this.apiClient.buildCollectionParam(opts['isOkNotifications'], 'csv'),
        'is_enabled': opts['isEnabled']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/heartbeats', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
