/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetAllTeamMembersLegacy200Response from '../model/GetAllTeamMembersLegacy200Response';
import GetTeamMemberLegacy200Response from '../model/GetTeamMemberLegacy200Response';
import MonitorsPost201Response from '../model/MonitorsPost201Response';

/**
* LegacyTeamMembers service.
* @module api/LegacyTeamMembersApi
* @version 1.0.0
*/
export default class LegacyTeamMembersApi {

    /**
    * Constructs a new LegacyTeamMembersApi. 
    * @alias module:api/LegacyTeamMembersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteTeamMemberLegacy operation.
     * @callback module:api/LegacyTeamMembersApi~deleteTeamMemberLegacyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete team member
     * @param {Number} teamMemberId 
     * @param {module:api/LegacyTeamMembersApi~deleteTeamMemberLegacyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTeamMemberLegacy(teamMemberId, callback) {
      let postBody = null;
      // verify the required parameter 'teamMemberId' is set
      if (teamMemberId === undefined || teamMemberId === null) {
        throw new Error("Missing the required parameter 'teamMemberId' when calling deleteTeamMemberLegacy");
      }

      let pathParams = {
        'team_member_id': teamMemberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/teams-member/{team_member_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllTeamMembersLegacy operation.
     * @callback module:api/LegacyTeamMembersApi~getAllTeamMembersLegacyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAllTeamMembersLegacy200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all team members
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] 
     * @param {module:model/Number} [resultsPerPage = 25)] 
     * @param {module:api/LegacyTeamMembersApi~getAllTeamMembersLegacyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAllTeamMembersLegacy200Response}
     */
    getAllTeamMembersLegacy(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAllTeamMembersLegacy200Response;
      return this.apiClient.callApi(
        '/teams-member', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTeamMemberLegacy operation.
     * @callback module:api/LegacyTeamMembersApi~getTeamMemberLegacyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetTeamMemberLegacy200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one team member
     * @param {Number} teamMemberId 
     * @param {module:api/LegacyTeamMembersApi~getTeamMemberLegacyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetTeamMemberLegacy200Response}
     */
    getTeamMemberLegacy(teamMemberId, callback) {
      let postBody = null;
      // verify the required parameter 'teamMemberId' is set
      if (teamMemberId === undefined || teamMemberId === null) {
        throw new Error("Missing the required parameter 'teamMemberId' when calling getTeamMemberLegacy");
      }

      let pathParams = {
        'team_member_id': teamMemberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetTeamMemberLegacy200Response;
      return this.apiClient.callApi(
        '/teams-member/{team_member_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTeamMemberLegacy operation.
     * @callback module:api/LegacyTeamMembersApi~updateTeamMemberLegacyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update team member
     * @param {Number} teamMemberId 
     * @param {Object} opts Optional parameters
     * @param {Boolean} [status] Enable or disable team member
     * @param {module:api/LegacyTeamMembersApi~updateTeamMemberLegacyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    updateTeamMemberLegacy(teamMemberId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'teamMemberId' is set
      if (teamMemberId === undefined || teamMemberId === null) {
        throw new Error("Missing the required parameter 'teamMemberId' when calling updateTeamMemberLegacy");
      }

      let pathParams = {
        'team_member_id': teamMemberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'status': opts['status']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/teams-member/{team_member_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
