/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MonitorsPost201Response from '../model/MonitorsPost201Response';
import NotificationHandlerGet200Response from '../model/NotificationHandlerGet200Response';
import NotificationHandlerNotificationHandlerIdGet200Response from '../model/NotificationHandlerNotificationHandlerIdGet200Response';

/**
* NotificationHandlers service.
* @module api/NotificationHandlersApi
* @version 1.0.0
*/
export default class NotificationHandlersApi {

    /**
    * Constructs a new NotificationHandlersApi. 
    * @alias module:api/NotificationHandlersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the notificationHandlerGet operation.
     * @callback module:api/NotificationHandlersApi~notificationHandlerGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NotificationHandlerGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all notification handlers
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/NotificationHandlersApi~notificationHandlerGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NotificationHandlerGet200Response}
     */
    notificationHandlerGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = NotificationHandlerGet200Response;
      return this.apiClient.callApi(
        '/notification-handler', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the notificationHandlerNotificationHandlerIdGet operation.
     * @callback module:api/NotificationHandlersApi~notificationHandlerNotificationHandlerIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NotificationHandlerNotificationHandlerIdGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one notification handler
     * @param {Number} notificationHandlerId 
     * @param {module:api/NotificationHandlersApi~notificationHandlerNotificationHandlerIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NotificationHandlerNotificationHandlerIdGet200Response}
     */
    notificationHandlerNotificationHandlerIdGet(notificationHandlerId, callback) {
      let postBody = null;
      // verify the required parameter 'notificationHandlerId' is set
      if (notificationHandlerId === undefined || notificationHandlerId === null) {
        throw new Error("Missing the required parameter 'notificationHandlerId' when calling notificationHandlerNotificationHandlerIdGet");
      }

      let pathParams = {
        'notification_handler_id': notificationHandlerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = NotificationHandlerNotificationHandlerIdGet200Response;
      return this.apiClient.callApi(
        '/notification-handler/{notification_handler_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the notificationHandlersNotificationHandlerIdDelete operation.
     * @callback module:api/NotificationHandlersApi~notificationHandlersNotificationHandlerIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete notification handler
     * @param {Number} notificationHandlerId 
     * @param {module:api/NotificationHandlersApi~notificationHandlersNotificationHandlerIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    notificationHandlersNotificationHandlerIdDelete(notificationHandlerId, callback) {
      let postBody = null;
      // verify the required parameter 'notificationHandlerId' is set
      if (notificationHandlerId === undefined || notificationHandlerId === null) {
        throw new Error("Missing the required parameter 'notificationHandlerId' when calling notificationHandlersNotificationHandlerIdDelete");
      }

      let pathParams = {
        'notification_handler_id': notificationHandlerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/notification-handlers/{notification_handler_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the notificationHandlersNotificationHandlerIdPost operation.
     * @callback module:api/NotificationHandlersApi~notificationHandlersNotificationHandlerIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update notification handler
     * @param {Number} notificationHandlerId 
     * @param {Object} opts Optional parameters
     * @param {String} [name] 
     * @param {module:model/String} [type] 
     * @param {String} [email] 
     * @param {String} [webhook] 
     * @param {String} [squadcast] 
     * @param {String} [googlechat] 
     * @param {String} [slack] 
     * @param {String} [discord] 
     * @param {String} [telegram] 
     * @param {String} [telegramChatId] 
     * @param {Boolean} [isEnabled] 
     * @param {module:api/NotificationHandlersApi~notificationHandlersNotificationHandlerIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    notificationHandlersNotificationHandlerIdPost(notificationHandlerId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'notificationHandlerId' is set
      if (notificationHandlerId === undefined || notificationHandlerId === null) {
        throw new Error("Missing the required parameter 'notificationHandlerId' when calling notificationHandlersNotificationHandlerIdPost");
      }

      let pathParams = {
        'notification_handler_id': notificationHandlerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': opts['name'],
        'type': opts['type'],
        'email': opts['email'],
        'webhook': opts['webhook'],
        'squadcast': opts['squadcast'],
        'googlechat': opts['googlechat'],
        'slack': opts['slack'],
        'discord': opts['discord'],
        'telegram': opts['telegram'],
        'telegram_chat_id': opts['telegramChatId'],
        'is_enabled': opts['isEnabled']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/notification-handlers/{notification_handler_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the notificationHandlersPost operation.
     * @callback module:api/NotificationHandlersApi~notificationHandlersPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create notification handler
     * @param {String} name 
     * @param {module:model/String} type 
     * @param {Object} opts Optional parameters
     * @param {String} [email] 
     * @param {String} [webhook] 
     * @param {String} [squadcast] 
     * @param {String} [googlechat] 
     * @param {String} [slack] 
     * @param {String} [discord] 
     * @param {String} [telegram] 
     * @param {String} [telegramChatId] 
     * @param {Boolean} [isEnabled] 
     * @param {module:api/NotificationHandlersApi~notificationHandlersPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    notificationHandlersPost(name, type, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling notificationHandlersPost");
      }
      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling notificationHandlersPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'type': type,
        'email': opts['email'],
        'webhook': opts['webhook'],
        'squadcast': opts['squadcast'],
        'googlechat': opts['googlechat'],
        'slack': opts['slack'],
        'discord': opts['discord'],
        'telegram': opts['telegram'],
        'telegram_chat_id': opts['telegramChatId'],
        'is_enabled': opts['isEnabled']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/notification-handlers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
