/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetAllServerMonitors200Response from '../model/GetAllServerMonitors200Response';
import GetServerMonitor200Response from '../model/GetServerMonitor200Response';

/**
* ServerMonitors service.
* @module api/ServerMonitorsApi
* @version 1.0.0
*/
export default class ServerMonitorsApi {

    /**
    * Constructs a new ServerMonitorsApi. 
    * @alias module:api/ServerMonitorsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteServerMonitor operation.
     * @callback module:api/ServerMonitorsApi~deleteServerMonitorCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete server monitor
     * Deletes a specific server monitor.
     * @param {Number} serverMonitorId 
     * @param {module:api/ServerMonitorsApi~deleteServerMonitorCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteServerMonitor(serverMonitorId, callback) {
      let postBody = null;
      // verify the required parameter 'serverMonitorId' is set
      if (serverMonitorId === undefined || serverMonitorId === null) {
        throw new Error("Missing the required parameter 'serverMonitorId' when calling deleteServerMonitor");
      }

      let pathParams = {
        'server_monitor_id': serverMonitorId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/server-monitors/{server_monitor_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllServerMonitors operation.
     * @callback module:api/ServerMonitorsApi~getAllServerMonitorsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAllServerMonitors200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all server monitors
     * Returns a paginated list of server monitors.
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/ServerMonitorsApi~getAllServerMonitorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAllServerMonitors200Response}
     */
    getAllServerMonitors(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAllServerMonitors200Response;
      return this.apiClient.callApi(
        '/server-monitors', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getServerMonitor operation.
     * @callback module:api/ServerMonitorsApi~getServerMonitorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetServerMonitor200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one server monitor
     * Returns details of a specific server monitor.
     * @param {Number} serverMonitorId 
     * @param {module:api/ServerMonitorsApi~getServerMonitorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetServerMonitor200Response}
     */
    getServerMonitor(serverMonitorId, callback) {
      let postBody = null;
      // verify the required parameter 'serverMonitorId' is set
      if (serverMonitorId === undefined || serverMonitorId === null) {
        throw new Error("Missing the required parameter 'serverMonitorId' when calling getServerMonitor");
      }

      let pathParams = {
        'server_monitor_id': serverMonitorId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetServerMonitor200Response;
      return this.apiClient.callApi(
        '/server-monitors/{server_monitor_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
