/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetAllStatusPages200Response from '../model/GetAllStatusPages200Response';
import GetStatusPage200Response from '../model/GetStatusPage200Response';

/**
* StatusPages service.
* @module api/StatusPagesApi
* @version 1.0.0
*/
export default class StatusPagesApi {

    /**
    * Constructs a new StatusPagesApi. 
    * @alias module:api/StatusPagesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllStatusPages operation.
     * @callback module:api/StatusPagesApi~getAllStatusPagesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAllStatusPages200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all status pages
     * Returns a paginated list of status pages.
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/StatusPagesApi~getAllStatusPagesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAllStatusPages200Response}
     */
    getAllStatusPages(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAllStatusPages200Response;
      return this.apiClient.callApi(
        '/status-pages', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getStatusPage operation.
     * @callback module:api/StatusPagesApi~getStatusPageCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetStatusPage200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve one status page
     * Returns details of a specific status page.
     * @param {Number} statusPageId 
     * @param {module:api/StatusPagesApi~getStatusPageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetStatusPage200Response}
     */
    getStatusPage(statusPageId, callback) {
      let postBody = null;
      // verify the required parameter 'statusPageId' is set
      if (statusPageId === undefined || statusPageId === null) {
        throw new Error("Missing the required parameter 'statusPageId' when calling getStatusPage");
      }

      let pathParams = {
        'status_page_id': statusPageId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetStatusPage200Response;
      return this.apiClient.callApi(
        '/status-pages/{status_page_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
