/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetStatusPageStatistics200Response from '../model/GetStatusPageStatistics200Response';

/**
* StatusPageStatistics service.
* @module api/StatusPageStatisticsApi
* @version 1.0.0
*/
export default class StatusPageStatisticsApi {

    /**
    * Constructs a new StatusPageStatisticsApi. 
    * @alias module:api/StatusPageStatisticsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getStatusPageStatistics operation.
     * @callback module:api/StatusPageStatisticsApi~getStatusPageStatisticsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetStatusPageStatistics200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve status page statistics
     * Returns analytics data for a specific status page based on date range and filters.
     * @param {Number} statusPageId 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [type] 
     * @param {String} [countryCode] 
     * @param {String} [utmSource] 
     * @param {String} [utmMedium] 
     * @param {module:api/StatusPageStatisticsApi~getStatusPageStatisticsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetStatusPageStatistics200Response}
     */
    getStatusPageStatistics(statusPageId, startDate, endDate, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'statusPageId' is set
      if (statusPageId === undefined || statusPageId === null) {
        throw new Error("Missing the required parameter 'statusPageId' when calling getStatusPageStatistics");
      }
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getStatusPageStatistics");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getStatusPageStatistics");
      }

      let pathParams = {
        'status_page_id': statusPageId
      };
      let queryParams = {
        'start_date': startDate,
        'end_date': endDate,
        'type': opts['type'],
        'country_code': opts['countryCode'],
        'utm_source': opts['utmSource'],
        'utm_medium': opts['utmMedium']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetStatusPageStatistics200Response;
      return this.apiClient.callApi(
        '/statistics/{status_page_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
