/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetTeamMembersByTeam200Response from '../model/GetTeamMembersByTeam200Response';
import MonitorsPost201Response from '../model/MonitorsPost201Response';

/**
* TeamMembers service.
* @module api/TeamMembersApi
* @version 1.0.0
*/
export default class TeamMembersApi {

    /**
    * Constructs a new TeamMembersApi. 
    * @alias module:api/TeamMembersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createTeamMember operation.
     * @callback module:api/TeamMembersApi~createTeamMemberCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create team member
     * @param {Number} teamId 
     * @param {String} userEmail 
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/String>} [access] 
     * @param {module:api/TeamMembersApi~createTeamMemberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    createTeamMember(teamId, userEmail, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'teamId' is set
      if (teamId === undefined || teamId === null) {
        throw new Error("Missing the required parameter 'teamId' when calling createTeamMember");
      }
      // verify the required parameter 'userEmail' is set
      if (userEmail === undefined || userEmail === null) {
        throw new Error("Missing the required parameter 'userEmail' when calling createTeamMember");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'team_id': teamId,
        'user_email': userEmail,
        'access': this.apiClient.buildCollectionParam(opts['access'], 'csv')
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/team-members', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTeamMember operation.
     * @callback module:api/TeamMembersApi~deleteTeamMemberCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete team member
     * @param {Number} teamMemberId 
     * @param {module:api/TeamMembersApi~deleteTeamMemberCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTeamMember(teamMemberId, callback) {
      let postBody = null;
      // verify the required parameter 'teamMemberId' is set
      if (teamMemberId === undefined || teamMemberId === null) {
        throw new Error("Missing the required parameter 'teamMemberId' when calling deleteTeamMember");
      }

      let pathParams = {
        'team_member_id': teamMemberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/team-members/{team_member_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTeamMembersByTeam operation.
     * @callback module:api/TeamMembersApi~getTeamMembersByTeamCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetTeamMembersByTeam200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve team members
     * @param {Number} teamId 
     * @param {module:api/TeamMembersApi~getTeamMembersByTeamCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetTeamMembersByTeam200Response}
     */
    getTeamMembersByTeam(teamId, callback) {
      let postBody = null;
      // verify the required parameter 'teamId' is set
      if (teamId === undefined || teamId === null) {
        throw new Error("Missing the required parameter 'teamId' when calling getTeamMembersByTeam");
      }

      let pathParams = {
        'team_id': teamId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetTeamMembersByTeam200Response;
      return this.apiClient.callApi(
        '/team-members/{team_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTeamMember operation.
     * @callback module:api/TeamMembersApi~updateTeamMemberCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update team member
     * @param {Number} teamMemberId 
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/String>} [access] 
     * @param {module:api/TeamMembersApi~updateTeamMemberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    updateTeamMember(teamMemberId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'teamMemberId' is set
      if (teamMemberId === undefined || teamMemberId === null) {
        throw new Error("Missing the required parameter 'teamMemberId' when calling updateTeamMember");
      }

      let pathParams = {
        'team_member_id': teamMemberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'access': this.apiClient.buildCollectionParam(opts['access'], 'csv')
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/team-members/{team_member_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
