/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MonitorsGet200Response from '../model/MonitorsGet200Response';
import MonitorsPost201Response from '../model/MonitorsPost201Response';

/**
* UptimeMonitors service.
* @module api/UptimeMonitorsApi
* @version 1.0.0
*/
export default class UptimeMonitorsApi {

    /**
    * Constructs a new UptimeMonitorsApi. 
    * @alias module:api/UptimeMonitorsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the monitorsGet operation.
     * @callback module:api/UptimeMonitorsApi~monitorsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all uptime monitors
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {module:model/Number} [resultsPerPage] 
     * @param {module:api/UptimeMonitorsApi~monitorsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsGet200Response}
     */
    monitorsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'results_per_page': opts['resultsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MonitorsGet200Response;
      return this.apiClient.callApi(
        '/monitors', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the monitorsPost operation.
     * @callback module:api/UptimeMonitorsApi~monitorsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MonitorsPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create uptime monitor
     * @param {String} name 
     * @param {String} target 
     * @param {Object} opts Optional parameters
     * @param {Number} [port] 
     * @param {module:model/String} [type] 
     * @param {Number} [projectId] 
     * @param {module:api/UptimeMonitorsApi~monitorsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MonitorsPost201Response}
     */
    monitorsPost(name, target, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling monitorsPost");
      }
      // verify the required parameter 'target' is set
      if (target === undefined || target === null) {
        throw new Error("Missing the required parameter 'target' when calling monitorsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'name': name,
        'target': target,
        'port': opts['port'],
        'type': opts['type'],
        'project_id': opts['projectId']
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = MonitorsPost201Response;
      return this.apiClient.callApi(
        '/monitors', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
