/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.DNSMonitorDns();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DNSMonitorDns', function() {
    it('should create an instance of DNSMonitorDns', function() {
      // uncomment below and update the code to test DNSMonitorDns
      //var instance = new HydrozenApi.DNSMonitorDns();
      //expect(instance).to.be.a(HydrozenApi.DNSMonitorDns);
    });

    it('should have the property A (base name: "A")', function() {
      // uncomment below and update the code to test the property A
      //var instance = new HydrozenApi.DNSMonitorDns();
      //expect(instance).to.be();
    });

    it('should have the property CNAME (base name: "CNAME")', function() {
      // uncomment below and update the code to test the property CNAME
      //var instance = new HydrozenApi.DNSMonitorDns();
      //expect(instance).to.be();
    });

    it('should have the property HINFO (base name: "HINFO")', function() {
      // uncomment below and update the code to test the property HINFO
      //var instance = new HydrozenApi.DNSMonitorDns();
      //expect(instance).to.be();
    });

    it('should have the property CAA (base name: "CAA")', function() {
      // uncomment below and update the code to test the property CAA
      //var instance = new HydrozenApi.DNSMonitorDns();
      //expect(instance).to.be();
    });

    it('should have the property MX (base name: "MX")', function() {
      // uncomment below and update the code to test the property MX
      //var instance = new HydrozenApi.DNSMonitorDns();
      //expect(instance).to.be();
    });

  });

}));
