/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.DNSMonitor();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DNSMonitor', function() {
    it('should create an instance of DNSMonitor', function() {
      // uncomment below and update the code to test DNSMonitor
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be.a(HydrozenApi.DNSMonitor);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property target (base name: "target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property dns (base name: "dns")', function() {
      // uncomment below and update the code to test the property dns
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property notifications (base name: "notifications")', function() {
      // uncomment below and update the code to test the property notifications
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property totalChecks (base name: "total_checks")', function() {
      // uncomment below and update the code to test the property totalChecks
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property totalChanges (base name: "total_changes")', function() {
      // uncomment below and update the code to test the property totalChanges
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property lastCheckDatetime (base name: "last_check_datetime")', function() {
      // uncomment below and update the code to test the property lastCheckDatetime
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property nextCheckDatetime (base name: "next_check_datetime")', function() {
      // uncomment below and update the code to test the property nextCheckDatetime
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property lastChangeDatetime (base name: "last_change_datetime")', function() {
      // uncomment below and update the code to test the property lastChangeDatetime
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "is_enabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property datetime (base name: "datetime")', function() {
      // uncomment below and update the code to test the property datetime
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

    it('should have the property lastDatetime (base name: "last_datetime")', function() {
      // uncomment below and update the code to test the property lastDatetime
      //var instance = new HydrozenApi.DNSMonitor();
      //expect(instance).to.be();
    });

  });

}));
