/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.HeartbeatMonitor();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HeartbeatMonitor', function() {
    it('should create an instance of HeartbeatMonitor', function() {
      // uncomment below and update the code to test HeartbeatMonitor
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be.a(HydrozenApi.HeartbeatMonitor);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property isOk (base name: "is_ok")', function() {
      // uncomment below and update the code to test the property isOk
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property uptime (base name: "uptime")', function() {
      // uncomment below and update the code to test the property uptime
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property downtime (base name: "downtime")', function() {
      // uncomment below and update the code to test the property downtime
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property totalRuns (base name: "total_runs")', function() {
      // uncomment below and update the code to test the property totalRuns
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property totalMissedRuns (base name: "total_missed_runs")', function() {
      // uncomment below and update the code to test the property totalMissedRuns
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property lastRunDatetime (base name: "last_run_datetime")', function() {
      // uncomment below and update the code to test the property lastRunDatetime
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property notifications (base name: "notifications")', function() {
      // uncomment below and update the code to test the property notifications
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "is_enabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

    it('should have the property datetime (base name: "datetime")', function() {
      // uncomment below and update the code to test the property datetime
      //var instance = new HydrozenApi.HeartbeatMonitor();
      //expect(instance).to.be();
    });

  });

}));
