/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.MonitorSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MonitorSettings', function() {
    it('should create an instance of MonitorSettings', function() {
      // uncomment below and update the code to test MonitorSettings
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be.a(HydrozenApi.MonitorSettings);
    });

    it('should have the property checkIntervalSeconds (base name: "check_interval_seconds")', function() {
      // uncomment below and update the code to test the property checkIntervalSeconds
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property timeoutSeconds (base name: "timeout_seconds")', function() {
      // uncomment below and update the code to test the property timeoutSeconds
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property requestMethod (base name: "request_method")', function() {
      // uncomment below and update the code to test the property requestMethod
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property requestBody (base name: "request_body")', function() {
      // uncomment below and update the code to test the property requestBody
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property requestBasicAuthUsername (base name: "request_basic_auth_username")', function() {
      // uncomment below and update the code to test the property requestBasicAuthUsername
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property requestBasicAuthPassword (base name: "request_basic_auth_password")', function() {
      // uncomment below and update the code to test the property requestBasicAuthPassword
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property requestHeaders (base name: "request_headers")', function() {
      // uncomment below and update the code to test the property requestHeaders
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property responseStatusCode (base name: "response_status_code")', function() {
      // uncomment below and update the code to test the property responseStatusCode
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property responseBody (base name: "response_body")', function() {
      // uncomment below and update the code to test the property responseBody
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

    it('should have the property responseHeaders (base name: "response_headers")', function() {
      // uncomment below and update the code to test the property responseHeaders
      //var instance = new HydrozenApi.MonitorSettings();
      //expect(instance).to.be();
    });

  });

}));
