/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.Monitor();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Monitor', function() {
    it('should create an instance of Monitor', function() {
      // uncomment below and update the code to test Monitor
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be.a(HydrozenApi.Monitor);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property target (base name: "target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property port (base name: "port")', function() {
      // uncomment below and update the code to test the property port
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property pingServersIds (base name: "ping_servers_ids")', function() {
      // uncomment below and update the code to test the property pingServersIds
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property isOk (base name: "is_ok")', function() {
      // uncomment below and update the code to test the property isOk
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property uptime (base name: "uptime")', function() {
      // uncomment below and update the code to test the property uptime
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property downtime (base name: "downtime")', function() {
      // uncomment below and update the code to test the property downtime
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property averageResponseTime (base name: "average_response_time")', function() {
      // uncomment below and update the code to test the property averageResponseTime
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property totalChecks (base name: "total_checks")', function() {
      // uncomment below and update the code to test the property totalChecks
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property totalOkChecks (base name: "total_ok_checks")', function() {
      // uncomment below and update the code to test the property totalOkChecks
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property totalNotOkChecks (base name: "total_not_ok_checks")', function() {
      // uncomment below and update the code to test the property totalNotOkChecks
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property lastCheckDatetime (base name: "last_check_datetime")', function() {
      // uncomment below and update the code to test the property lastCheckDatetime
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property notifications (base name: "notifications")', function() {
      // uncomment below and update the code to test the property notifications
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "is_enabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

    it('should have the property datetime (base name: "datetime")', function() {
      // uncomment below and update the code to test the property datetime
      //var instance = new HydrozenApi.Monitor();
      //expect(instance).to.be();
    });

  });

}));
