/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.NotificationHandlerSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotificationHandlerSettings', function() {
    it('should create an instance of NotificationHandlerSettings', function() {
      // uncomment below and update the code to test NotificationHandlerSettings
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be.a(HydrozenApi.NotificationHandlerSettings);
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

    it('should have the property webhook (base name: "webhook")', function() {
      // uncomment below and update the code to test the property webhook
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

    it('should have the property squadcast (base name: "squadcast")', function() {
      // uncomment below and update the code to test the property squadcast
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

    it('should have the property googlechat (base name: "googlechat")', function() {
      // uncomment below and update the code to test the property googlechat
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

    it('should have the property slack (base name: "slack")', function() {
      // uncomment below and update the code to test the property slack
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

    it('should have the property discord (base name: "discord")', function() {
      // uncomment below and update the code to test the property discord
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

    it('should have the property telegram (base name: "telegram")', function() {
      // uncomment below and update the code to test the property telegram
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

    it('should have the property telegramChatId (base name: "telegram_chat_id")', function() {
      // uncomment below and update the code to test the property telegramChatId
      //var instance = new HydrozenApi.NotificationHandlerSettings();
      //expect(instance).to.be();
    });

  });

}));
