/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.ServerMonitor();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServerMonitor', function() {
    it('should create an instance of ServerMonitor', function() {
      // uncomment below and update the code to test ServerMonitor
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be.a(HydrozenApi.ServerMonitor);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property target (base name: "target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property cpuUsage (base name: "cpu_usage")', function() {
      // uncomment below and update the code to test the property cpuUsage
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property ramUsage (base name: "ram_usage")', function() {
      // uncomment below and update the code to test the property ramUsage
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property diskUsage (base name: "disk_usage")', function() {
      // uncomment below and update the code to test the property diskUsage
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property cpuLoad1 (base name: "cpu_load_1")', function() {
      // uncomment below and update the code to test the property cpuLoad1
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property cpuLoad5 (base name: "cpu_load_5")', function() {
      // uncomment below and update the code to test the property cpuLoad5
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property cpuLoad15 (base name: "cpu_load_15")', function() {
      // uncomment below and update the code to test the property cpuLoad15
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "is_enabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property totalLogs (base name: "total_logs")', function() {
      // uncomment below and update the code to test the property totalLogs
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property lastLogDatetime (base name: "last_log_datetime")', function() {
      // uncomment below and update the code to test the property lastLogDatetime
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property datetime (base name: "datetime")', function() {
      // uncomment below and update the code to test the property datetime
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

    it('should have the property lastDatetime (base name: "last_datetime")', function() {
      // uncomment below and update the code to test the property lastDatetime
      //var instance = new HydrozenApi.ServerMonitor();
      //expect(instance).to.be();
    });

  });

}));
