/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.StatusPage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StatusPage', function() {
    it('should create an instance of StatusPage', function() {
      // uncomment below and update the code to test StatusPage
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be.a(HydrozenApi.StatusPage);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property domainId (base name: "domain_id")', function() {
      // uncomment below and update the code to test the property domainId
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property monitorsIds (base name: "monitors_ids")', function() {
      // uncomment below and update the code to test the property monitorsIds
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property fullUrl (base name: "full_url")', function() {
      // uncomment below and update the code to test the property fullUrl
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property socials (base name: "socials")', function() {
      // uncomment below and update the code to test the property socials
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property logoUrl (base name: "logo_url")', function() {
      // uncomment below and update the code to test the property logoUrl
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property faviconUrl (base name: "favicon_url")', function() {
      // uncomment below and update the code to test the property faviconUrl
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property timezone (base name: "timezone")', function() {
      // uncomment below and update the code to test the property timezone
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property customJs (base name: "custom_js")', function() {
      // uncomment below and update the code to test the property customJs
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property customCss (base name: "custom_css")', function() {
      // uncomment below and update the code to test the property customCss
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property pageviews (base name: "pageviews")', function() {
      // uncomment below and update the code to test the property pageviews
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property isSeVisible (base name: "is_se_visible")', function() {
      // uncomment below and update the code to test the property isSeVisible
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property isRemovedBranding (base name: "is_removed_branding")', function() {
      // uncomment below and update the code to test the property isRemovedBranding
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "is_enabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

    it('should have the property datetime (base name: "datetime")', function() {
      // uncomment below and update the code to test the property datetime
      //var instance = new HydrozenApi.StatusPage();
      //expect(instance).to.be();
    });

  });

}));
