/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be.a(HydrozenApi.User);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property billing (base name: "billing")', function() {
      // uncomment below and update the code to test the property billing
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "is_enabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property planId (base name: "plan_id")', function() {
      // uncomment below and update the code to test the property planId
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property planExpirationDate (base name: "plan_expiration_date")', function() {
      // uncomment below and update the code to test the property planExpirationDate
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property planSettings (base name: "plan_settings")', function() {
      // uncomment below and update the code to test the property planSettings
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property planTrialDone (base name: "plan_trial_done")', function() {
      // uncomment below and update the code to test the property planTrialDone
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property timezone (base name: "timezone")', function() {
      // uncomment below and update the code to test the property timezone
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property lastActivity (base name: "last_activity")', function() {
      // uncomment below and update the code to test the property lastActivity
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

    it('should have the property totalLogins (base name: "total_logins")', function() {
      // uncomment below and update the code to test the property totalLogins
      //var instance = new HydrozenApi.User();
      //expect(instance).to.be();
    });

  });

}));
