/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.DomainMonitorsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DomainMonitorsApi', function() {
    describe('domainNamesDomainNameIdDelete', function() {
      it('should call domainNamesDomainNameIdDelete successfully', function(done) {
        //uncomment below and update the code to test domainNamesDomainNameIdDelete
        //instance.domainNamesDomainNameIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainNamesDomainNameIdGet', function() {
      it('should call domainNamesDomainNameIdGet successfully', function(done) {
        //uncomment below and update the code to test domainNamesDomainNameIdGet
        //instance.domainNamesDomainNameIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainNamesDomainNameIdPost', function() {
      it('should call domainNamesDomainNameIdPost successfully', function(done) {
        //uncomment below and update the code to test domainNamesDomainNameIdPost
        //instance.domainNamesDomainNameIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainNamesGet', function() {
      it('should call domainNamesGet successfully', function(done) {
        //uncomment below and update the code to test domainNamesGet
        //instance.domainNamesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainNamesPost', function() {
      it('should call domainNamesPost successfully', function(done) {
        //uncomment below and update the code to test domainNamesPost
        //instance.domainNamesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
