/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.HeartbeatMonitorsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HeartbeatMonitorsApi', function() {
    describe('heartbeatsGet', function() {
      it('should call heartbeatsGet successfully', function(done) {
        //uncomment below and update the code to test heartbeatsGet
        //instance.heartbeatsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('heartbeatsHeartbeatIdDelete', function() {
      it('should call heartbeatsHeartbeatIdDelete successfully', function(done) {
        //uncomment below and update the code to test heartbeatsHeartbeatIdDelete
        //instance.heartbeatsHeartbeatIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('heartbeatsHeartbeatIdGet', function() {
      it('should call heartbeatsHeartbeatIdGet successfully', function(done) {
        //uncomment below and update the code to test heartbeatsHeartbeatIdGet
        //instance.heartbeatsHeartbeatIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('heartbeatsHeartbeatIdPost', function() {
      it('should call heartbeatsHeartbeatIdPost successfully', function(done) {
        //uncomment below and update the code to test heartbeatsHeartbeatIdPost
        //instance.heartbeatsHeartbeatIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('heartbeatsPost', function() {
      it('should call heartbeatsPost successfully', function(done) {
        //uncomment below and update the code to test heartbeatsPost
        //instance.heartbeatsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
