/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.LegacyTeamMembersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LegacyTeamMembersApi', function() {
    describe('deleteTeamMemberLegacy', function() {
      it('should call deleteTeamMemberLegacy successfully', function(done) {
        //uncomment below and update the code to test deleteTeamMemberLegacy
        //instance.deleteTeamMemberLegacy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllTeamMembersLegacy', function() {
      it('should call getAllTeamMembersLegacy successfully', function(done) {
        //uncomment below and update the code to test getAllTeamMembersLegacy
        //instance.getAllTeamMembersLegacy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeamMemberLegacy', function() {
      it('should call getTeamMemberLegacy successfully', function(done) {
        //uncomment below and update the code to test getTeamMemberLegacy
        //instance.getTeamMemberLegacy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTeamMemberLegacy', function() {
      it('should call updateTeamMemberLegacy successfully', function(done) {
        //uncomment below and update the code to test updateTeamMemberLegacy
        //instance.updateTeamMemberLegacy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
