/**
 * Hydrozen API
 * The Hydrozen API allows developers to programmatically manage monitors, projects, teams, payments, and status pages. All endpoints require Bearer authentication using an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HydrozenApi);
  }
}(this, function(expect, HydrozenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HydrozenApi.NotificationHandlersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotificationHandlersApi', function() {
    describe('notificationHandlerGet', function() {
      it('should call notificationHandlerGet successfully', function(done) {
        //uncomment below and update the code to test notificationHandlerGet
        //instance.notificationHandlerGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notificationHandlerNotificationHandlerIdGet', function() {
      it('should call notificationHandlerNotificationHandlerIdGet successfully', function(done) {
        //uncomment below and update the code to test notificationHandlerNotificationHandlerIdGet
        //instance.notificationHandlerNotificationHandlerIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notificationHandlersNotificationHandlerIdDelete', function() {
      it('should call notificationHandlersNotificationHandlerIdDelete successfully', function(done) {
        //uncomment below and update the code to test notificationHandlersNotificationHandlerIdDelete
        //instance.notificationHandlersNotificationHandlerIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notificationHandlersNotificationHandlerIdPost', function() {
      it('should call notificationHandlersNotificationHandlerIdPost successfully', function(done) {
        //uncomment below and update the code to test notificationHandlersNotificationHandlerIdPost
        //instance.notificationHandlersNotificationHandlerIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notificationHandlersPost', function() {
      it('should call notificationHandlersPost successfully', function(done) {
        //uncomment below and update the code to test notificationHandlersPost
        //instance.notificationHandlersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
